using System.Text;
using XafLogicExplainer.Core.Interfaces;
using XafLogicExplainer.Core.Models;

namespace XafLogicExplainer.Core.Generators;

/// <summary>
/// Builds the always-loaded index that teaches an AI coding agent about one specific XAF application.
/// </summary>
/// <remarks>
/// <para>
/// This is deliberately not the full documentation. An <c>AGENTS.md</c> is prepended to every
/// conversation an agent has in the repository, so its cost is paid on every request forever.
/// Sixty thousand characters of entity detail there would crowd out the user's actual question and
/// bury the few facts that change an answer.
/// </para>
/// <para>
/// So the output is tiered. This file produces a compact map: what the application is, what
/// definitively exists in it, the conventions it follows, and where the detail lives. The detail
/// itself goes to separate files the agent opens only when a question needs them.
/// </para>
/// <para>
/// The highest-value section is <em>Ground rules</em>, and specifically the closed-world statement.
/// Telling an agent that an inventory is complete converts "I did not find it" into "it does not
/// exist", which is the single most effective thing a document can do to stop invention.
/// </para>
/// <para>
/// Scaffolding text is English regardless of the <c>--lang</c> setting: these are instructions
/// addressed to a model, and English is where instruction-following is most reliable. The content
/// woven into them — entity names, captions, descriptions — stays in whatever language the
/// codebase is written in.
/// </para>
/// </remarks>
public sealed class AgentContextGenerator
{
    /// <summary>Longest criteria expression reproduced verbatim in the index.</summary>
    private const int MaxCriteriaLength = 160;

    /// <summary>How many criteria examples earn a place in the always-loaded tier.</summary>
    private const int MaxCriteriaExamples = 12;

    /// <summary>Directory, relative to the output root, holding the on-demand detail files.</summary>
    public const string DetailFolder = ".xaflogic";

    private readonly string _toolVersion;

    /// <summary>
    /// Creates a generator.
    /// </summary>
    /// <param name="toolVersion">Version stamped into the provenance header.</param>
    public AgentContextGenerator(string toolVersion = "0.9.0")
    {
        _toolVersion = toolVersion;
    }

    /// <summary>
    /// Generates the body of <c>AGENTS.md</c>.
    /// </summary>
    /// <param name="project">The extracted application.</param>
    /// <param name="detailFiles">
    /// File names written into <see cref="DetailFolder"/>, so the index can point at them.
    /// </param>
    public string GenerateIndex(ExtractedProject project, IReadOnlyList<string> detailFiles)
    {
        var conventions = CodebaseConventions.Infer(project);
        var sb = new StringBuilder();

        WriteHeader(sb, project);
        WriteSummary(sb, project);
        WriteGroundRules(sb, project, conventions);
        WriteEntityInventory(sb, project);
        WriteOperationsInventory(sb, project);
        WriteNavigation(sb, project);
        WriteCriteriaExamples(sb, conventions);
        WriteEditors(sb, project);
        WriteMigrations(sb, project);
        WriteConventions(sb, project, conventions);
        WriteRecipes(sb, project, conventions);
        WriteDetailPointers(sb, detailFiles);
        WriteFooter(sb);

        return sb.ToString();
    }

    /// <summary>
    /// Generates the ground-rules block on its own.
    /// </summary>
    /// <remarks>
    /// GitHub Copilot's instructions file has no import mechanism, so it cannot point at
    /// <c>AGENTS.md</c> the way Claude Code can. This block is small enough to inline there and
    /// carries most of the anti-hallucination value on its own.
    /// </remarks>
    public string GenerateGroundRules(ExtractedProject project)
    {
        var sb = new StringBuilder();
        WriteGroundRules(
            sb,
            project,
            CodebaseConventions.Infer(project),
            asSection: false,
            // Copilot's instructions file carries the rules but not the tables, so pointing at
            // "this file" would send the reader looking for inventories that are not there.
            inventoryLocation: "in `AGENTS.md`");
        return sb.ToString();
    }

    // ---------------------------------------------------------------- header

    private void WriteHeader(StringBuilder sb, ExtractedProject project)
    {
        sb.AppendLine($"# {project.ProjectName} — application context for AI agents");
        sb.AppendLine();
        sb.AppendLine("<!--");
        sb.AppendLine($"  Generated by XAF Logic Explainer {_toolVersion} on {project.ExtractedAt}");
        sb.AppendLine($"  Source fingerprint: {Short(project.SourceHash)}");

        if (!string.IsNullOrWhiteSpace(project.CatalogVersion))
            sb.AppendLine($"  Checked against the DevExpress {project.CatalogVersion} framework catalog");
        sb.AppendLine();
        sb.AppendLine("  This file is generated from source. Edits are overwritten.");
        sb.AppendLine("  Refresh it with:  xaflogic agents --project <module path>");
        sb.AppendLine("-->");
        sb.AppendLine();
    }

    private static void WriteSummary(StringBuilder sb, ExtractedProject project)
    {
        var actionCount = project.Controllers.Sum(c => c.Actions.Count);
        var orm = Orm.DisplayName(project.OrmType);

        sb.Append($"A DevExpress XAF application: **{project.Entities.Count} business ");
        sb.Append(Plural(project.Entities.Count, "entity", "entities"));
        sb.Append($"**, **{project.Controllers.Count} {Plural(project.Controllers.Count, "controller", "controllers")}**");

        if (actionCount > 0)
            sb.Append($" exposing **{actionCount} {Plural(actionCount, "action", "actions")}**");

        sb.Append($", persisted with **{orm}**");

        if (!string.IsNullOrWhiteSpace(project.TargetFramework))
            sb.Append($", targeting **{project.TargetFramework}**");

        sb.AppendLine(".");
        sb.AppendLine();

        if (project.ModuleInfo is { } module && !string.IsNullOrWhiteSpace(module.ModuleClassName))
        {
            sb.AppendLine($"The XAF module class is `{module.ModuleClassName}`.");

            if (module.RequiredModules.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("Required XAF modules:");
                sb.AppendLine();
                foreach (var required in module.RequiredModules.OrderBy(m => m, StringComparer.Ordinal))
                    sb.AppendLine($"- `{required}`");
            }

            sb.AppendLine();
        }
    }

    // ----------------------------------------------------------- ground rules

    private static void WriteGroundRules(
        StringBuilder sb,
        ExtractedProject project,
        CodebaseConventions conventions,
        bool asSection = true,
        string inventoryLocation = "in this file")
    {
        if (asSection)
        {
            sb.AppendLine("## Ground rules");
            sb.AppendLine();
            sb.AppendLine("These constrain every answer about this codebase.");
            sb.AppendLine();
        }

        var isEfCore = Orm.IsEfCore(project.OrmType);
        var rule = 1;

        // Rule 1: the ORM. Mixing XPO and EF Core idioms is the most frequent way generated XAF
        // code turns out wrong, because both are legitimate XAF and the class names collide --
        // BaseObject exists in both, in different namespaces.
        //
        // Which is why it is not written at all when the source never said. The rule forbids one
        // ORM outright, so stating it on a default would forbid whichever one the application
        // actually uses -- worse than silence, because the agent cannot tell a guess from a
        // reading.
        if (Orm.IsUnknown(project.OrmType))
        {
            sb.AppendLine($"**{rule++}. The ORM this application uses could not be determined.**");
            sb.AppendLine("No `DbSet<T>` registration, `DbContext`, XPO base class or ORM `using` directive was");
            sb.AppendLine("found in the analyzed source — so neither persistence style is ruled out here. Check");
            sb.AppendLine("what the project actually references before suggesting `Session`/`XPCollection` or");
            sb.AppendLine("`DbContext`/`DbSet<T>`, and do not infer one from the other files in this document.");
        }
        else if (isEfCore)
        {
            sb.AppendLine($"**{rule++}. Persistence is Entity Framework Core, not XPO.**");
            sb.AppendLine("`Session`, `XPObject`, `XPCollection`, `UnitOfWork` and `XPO` criteria APIs do not exist");
            sb.AppendLine("in this application and must never be suggested. Entities are mapped through a");
            sb.AppendLine("`DbContext`, and XAF reaches them through `IObjectSpace`");
            sb.AppendLine("(`GetObjects<T>()`, `CreateObject<T>()`, `CommitChanges()`).");
        }
        else
        {
            sb.AppendLine($"**{rule++}. Persistence is DevExpress XPO, not Entity Framework.**");
            sb.AppendLine("`DbContext`, `DbSet<T>`, `OnModelCreating`, EF migrations and EF-style data annotations");
            sb.AppendLine("do not exist in this application and must never be suggested. Collections are");
            sb.AppendLine("`XPCollection<T>`, and data access goes through `IObjectSpace`");
            sb.AppendLine("(`GetObjects<T>()`, `CreateObject<T>()`, `CommitChanges()`) or a `Session`.");
        }

        sb.AppendLine();

        // Rule 2: the closed-world statement. This is the load-bearing one.
        sb.AppendLine($"**{rule++}. The inventories {inventoryLocation} are complete.**");
        sb.AppendLine("They were extracted from the whole source tree, not sampled. If an entity, controller or");
        sb.AppendLine("action does not appear there, it does not exist in this application — say so plainly rather");
        sb.AppendLine("than assuming it lives in a file you have not opened. When a request needs something that");
        sb.AppendLine("is genuinely absent, the honest answer is that it must be created.");
        sb.AppendLine();

        // Rule 3: local conventions beat tutorials.
        if (conventions.DominantEntityBaseType is { } baseType)
        {
            sb.AppendLine($"**{rule++}. Follow this codebase, not generic XAF tutorials.**");
            sb.AppendLine($"Persistent classes here derive from `{baseType}`, and the *Conventions* section below");
            sb.AppendLine("records how this team writes associations, calculated properties and validation. Match");
            sb.AppendLine("what is already here; XAF usually offers several ways to express the same idea, and the");
            sb.AppendLine("one already in use is the correct one.");
            sb.AppendLine();
        }

        // Rule 4: the Model Editor -- invisible customizations that make C#-only reading wrong.
        if (conventions.HasModelEditorCustomizations)
        {
            sb.AppendLine($"**{rule++}. Some behavior lives in the Model Editor, not in C#.**");
            sb.AppendLine("This application has `.xafml` customizations: captions, list columns, filters and view");
            sb.AppendLine("settings that override what the C# suggests. Before concluding how a screen behaves from");
            sb.AppendLine($"the business classes alone, check the Model Editor detail in `{DetailFolder}/`.");
            sb.AppendLine();
        }

        // Rule: custom editors. A property with one does not render the way its type says, and the
        // editor lives in a platform project the reader may never open.
        if (project.Editors.Count > 0 || project.Controllers.Any(c => c.CustomizedEditors.Count > 0))
        {
            sb.AppendLine($"**{rule++}. Some screens do not follow their property types.**");
            sb.AppendLine("This application defines custom property or list editors, listed under *Custom editors*");
            sb.AppendLine("below. A property they render does **not** show the control its type implies, and the");
            sb.AppendLine("business class says nothing about it — the editor lives in a platform project beside the");
            sb.AppendLine("module. Check that list before describing or changing how anything appears on screen.");
            sb.AppendLine();
        }

        // Rule 5: staleness. Generated context that quietly goes out of date is worse than none.
        sb.AppendLine($"**{rule}. This file can go stale.**");
        sb.AppendLine("It reflects the source as of the timestamp in the header. If the code you are reading");
        sb.AppendLine("disagrees with this file, the code is right — and the file should be regenerated with");
        sb.AppendLine("`xaflogic agents`.");
        sb.AppendLine();
    }

    // ------------------------------------------------------------ inventories

    private static void WriteEntityInventory(StringBuilder sb, ExtractedProject project)
    {
        if (project.Entities.Count == 0)
            return;

        sb.AppendLine($"## Business entities ({project.Entities.Count} — complete)");
        sb.AppendLine();
        sb.AppendLine("| Entity | Base | Notable properties | Relationships |");
        sb.AppendLine("| --- | --- | --- | --- |");

        foreach (var entity in project.Entities.OrderBy(e => e.ClassName, StringComparer.Ordinal))
        {
            var notable = entity.Properties
                .Where(p => !p.IsCollection)
                .OrderByDescending(p => p.IsKey)
                .ThenByDescending(p => p.IsRequired)
                .ThenByDescending(p => p.IsComputed)
                .Take(5)
                .Select(p => $"`{p.Name}`{PropertyMarkers(p)}");

            var relationships = entity.Relationships
                .Take(4)
                .Select(r => $"{RelationshipArrow(r.Type)} `{r.RelatedEntity}`{(r.IsAggregated ? " (owned)" : "")}");

            var more = entity.Relationships.Count > 4 ? $" +{entity.Relationships.Count - 4}" : "";

            sb.Append($"| **{entity.ClassName}** ");
            sb.Append($"| `{Cell(entity.BaseType)}` ");
            sb.Append($"| {Cell(string.Join(", ", notable))} ");
            sb.AppendLine($"| {Cell(string.Join(", ", relationships) + more)} |");
        }

        sb.AppendLine();
        sb.AppendLine("Markers: `*` required · `=` calculated · `#` key.");
        sb.AppendLine();
    }

    private static void WriteOperationsInventory(StringBuilder sb, ExtractedProject project)
    {
        var withActions = project.Controllers.Where(c => c.Actions.Count > 0).ToList();
        var actionCount = withActions.Sum(c => c.Actions.Count);

        sb.AppendLine($"## Business operations ({actionCount} {Plural(actionCount, "action", "actions")} — complete)");
        sb.AppendLine();

        if (actionCount == 0)
        {
            sb.AppendLine("This application defines no custom actions. Its controllers, if any, customize behavior");
            sb.AppendLine("without adding commands to the UI.");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("| Action | Type | Controller | Applies to |");
            sb.AppendLine("| --- | --- | --- | --- |");

            foreach (var controller in withActions.OrderBy(c => c.ClassName, StringComparer.Ordinal))
            {
                foreach (var action in controller.Actions)
                {
                    var caption = string.IsNullOrWhiteSpace(action.Caption) ? action.ActionId : action.Caption;
                    var target = controller.TargetObjectType ?? "any view";

                    sb.Append($"| **{Cell(caption)}** ");
                    sb.Append($"| {Cell(ShortActionType(action.ActionType))} ");
                    sb.Append($"| `{Cell(controller.ClassName)}` ");
                    sb.AppendLine($"| {Cell(target)} |");
                }
            }

            sb.AppendLine();
            sb.AppendLine($"What each action *does* — including its handler code — is in `{DetailFolder}/`.");
            sb.AppendLine();
        }

        // Controllers without actions still matter: they change behavior invisibly, and an agent
        // that only reads the action table would conclude they do nothing.
        var silent = project.Controllers.Where(c => c.Actions.Count == 0).ToList();
        if (silent.Count > 0)
        {
            sb.AppendLine($"{silent.Count} further {Plural(silent.Count, "controller", "controllers")} define no actions but still");
            sb.AppendLine("customize behavior (view events, defaults, filtering):");
            sb.AppendLine();
            foreach (var controller in silent.OrderBy(c => c.ClassName, StringComparer.Ordinal))
            {
                var target = string.IsNullOrWhiteSpace(controller.TargetObjectType)
                    ? ""
                    : $" — targets `{controller.TargetObjectType}`";
                sb.AppendLine($"- `{controller.ClassName}`{target}");
            }
            sb.AppendLine();
        }

        WriteFrameworkExtensions(sb, project);
    }

    /// <summary>
    /// Names the controllers that extend shipped DevExpress behavior rather than starting fresh.
    /// </summary>
    /// <remarks>
    /// Only produced when a ground-truth catalog was available. The distinction matters: changing
    /// a controller that overrides <c>DeleteObjectsViewController</c> is changing how deletion
    /// works across the application, which is not obvious from the class alone.
    /// </remarks>
    private static void WriteFrameworkExtensions(StringBuilder sb, ExtractedProject project)
    {
        var extending = project.Controllers
            .Where(c => !string.IsNullOrWhiteSpace(c.FrameworkBaseType))
            .OrderBy(c => c.ClassName, StringComparer.Ordinal)
            .ToList();

        if (extending.Count == 0)
            return;

        sb.AppendLine("### Extending built-in DevExpress behavior");
        sb.AppendLine();
        sb.AppendLine("These derive from framework controllers, so they modify behavior XAF already provides:");
        sb.AppendLine();

        foreach (var controller in extending)
        {
            sb.Append($"- `{controller.ClassName}` extends **{controller.FrameworkBaseType}**");

            if (!string.IsNullOrWhiteSpace(controller.FrameworkBaseSummary))
                sb.Append($" — {Cell(controller.FrameworkBaseSummary)}");

            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(controller.FrameworkBaseDocumentationUrl))
                sb.AppendLine($"  - {controller.FrameworkBaseDocumentationUrl}");
        }

        sb.AppendLine();
    }

    private static void WriteNavigation(StringBuilder sb, ExtractedProject project)
    {
        if (project.Navigation.Count == 0)
            return;

        sb.AppendLine("## Navigation");
        sb.AppendLine();
        sb.AppendLine("What a user sees in the menu, which is usually how they will describe a screen to you:");
        sb.AppendLine();

        foreach (var group in project.Navigation)
        {
            sb.AppendLine($"- **{group.GroupName}** — {string.Join(", ", group.EntityClassNames.Select(e => $"`{e}`"))}");
        }

        sb.AppendLine();
    }

    private static void WriteCriteriaExamples(StringBuilder sb, CodebaseConventions conventions)
    {
        if (conventions.CriteriaExamples.Count == 0)
            return;

        sb.AppendLine("## Criteria expressions used here");
        sb.AppendLine();
        sb.AppendLine("XAF filters, validates and styles with criteria strings, which are neither SQL nor C#.");
        sb.AppendLine("These are real expressions from this codebase — follow their dialect:");
        sb.AppendLine();
        sb.AppendLine("```");

        foreach (var example in conventions.CriteriaExamples.Take(MaxCriteriaExamples))
        {
            sb.AppendLine($"// {example.Context}");
            sb.AppendLine(Truncate(example.Expression, MaxCriteriaLength));
            sb.AppendLine();
        }

        sb.AppendLine("```");
        sb.AppendLine();

        if (conventions.CriteriaExamples.Count > MaxCriteriaExamples)
        {
            var remaining = conventions.CriteriaExamples.Count - MaxCriteriaExamples;
            sb.AppendLine($"({remaining} further {Plural(remaining, "expression", "expressions")} in `{DetailFolder}/`.)");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Lists the editors that make a screen differ from what its property type implies.
    /// </summary>
    /// <remarks>
    /// Earns its place in the always-loaded tier because it changes answers about the UI, and
    /// because nothing else in this file hints that the control is not the standard one.
    /// </remarks>
    private static void WriteEditors(StringBuilder sb, ExtractedProject project)
    {
        var customized = project.Controllers.Where(c => c.CustomizedEditors.Count > 0).ToList();

        if (project.Editors.Count == 0 && customized.Count == 0)
            return;

        sb.AppendLine("## Custom editors");
        sb.AppendLine();
        sb.AppendLine("Properties these render do not show the control their type implies:");
        sb.AppendLine();

        foreach (var editor in project.Editors.OrderBy(e => e.ClassName, StringComparer.Ordinal))
        {
            sb.Append($"- **{editor.ClassName}** ({Describe(editor.Kind)})");

            if (!string.IsNullOrWhiteSpace(editor.TargetType))
                sb.Append($" for `{editor.TargetType}`");

            // The alias is what the editor *offers*, not evidence that anything asks for it. The
            // index said "requested with [EditorAlias(...)]" while the explainer, from the same
            // extraction, said "nothing requests it by alias" -- and the index is the file read on
            // every request.
            if (editor.IsDefault)
                sb.Append(" — **replaces the default everywhere**");
            else if (editor.UsedBy.Count > 0 && !string.IsNullOrWhiteSpace(editor.Alias))
                sb.Append($" — requested with `[EditorAlias(\"{editor.Alias}\")]`");
            else if (!string.IsNullOrWhiteSpace(editor.Alias))
                sb.Append($" — registered as `\"{editor.Alias}\"`, and no property asks for it");

            sb.AppendLine();

            if (editor.UsedBy.Count > 0)
                sb.AppendLine($"  - used by {string.Join(", ", editor.UsedBy.Select(u => $"`{u}`"))}");

            if (editor.ClientAssets.Count > 0)
                sb.AppendLine($"  - needs {string.Join(", ", editor.ClientAssets.Select(a => $"`{a}`"))} — behavior in neither C# nor XML");

            if (!string.IsNullOrWhiteSpace(editor.SourceProject))
                sb.AppendLine($"  - defined in `{editor.SourceProject}`, not in the module");
        }

        if (customized.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("These controllers reconfigure a **built-in** editor at run time, so there is no custom");
            sb.AppendLine("editor class to find and nothing on the entity records it:");
            sb.AppendLine();

            foreach (var controller in customized.OrderBy(c => c.ClassName, StringComparer.Ordinal))
                sb.AppendLine($"- `{controller.ClassName}` changes {string.Join(", ", controller.CustomizedEditors.Select(e => $"`{e}`"))}");
        }

        sb.AppendLine();
    }

    private static string Describe(EditorKind kind) => kind switch
    {
        EditorKind.PropertyEditor => "property editor",
        EditorKind.ListEditor => "list editor",
        EditorKind.ViewItem => "view item",
        _ => "editor",
    };

    /// <summary>
    /// Lists what happened to the data between released versions.
    /// </summary>
    /// <remarks>
    /// Belongs in the always-loaded tier because it prevents a specific wrong answer: asked why a
    /// column holds what it holds, an agent will reason from code that runs today and invent a
    /// cause. The real one ran once, years ago, and only the updater remembers it.
    /// </remarks>
    private static void WriteMigrations(StringBuilder sb, ExtractedProject project)
    {
        if (project.Migrations.Count == 0)
            return;

        sb.AppendLine("## Data migrations");
        sb.AppendLine();
        sb.AppendLine("Each runs **at most once** for any database, when it is upgraded past the version");
        sb.AppendLine("named, and never again after that. They explain");
        sb.AppendLine("data that the code running today does not account for:");
        sb.AppendLine();

        foreach (var migration in project.Migrations.OrderBy(m => m.TargetVersion, StringComparer.Ordinal))
        {
            sb.Append($"- **Upgrading to {migration.TargetVersion ?? "an unknown version"}**");

            if (migration.Phase != MigrationPhase.Unknown)
            {
                sb.Append(migration.Phase == MigrationPhase.BeforeSchemaUpdate
                    ? " (before the schema changed)"
                    : " (after the schema changed)");
            }

            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(migration.Description))
                sb.AppendLine($"  - {Cell(migration.Description)}");

            if (migration.CallsMethods.Count > 0)
                sb.AppendLine($"  - calls {string.Join(", ", migration.CallsMethods.Select(m => $"`{m}`"))}");
        }

        sb.AppendLine();
    }

    private static void WriteConventions(
        StringBuilder sb,
        ExtractedProject project,
        CodebaseConventions conventions)
    {
        sb.AppendLine("## Conventions observed in this codebase");
        sb.AppendLine();
        sb.AppendLine("Inferred from the source, not from XAF documentation. New code should match these.");
        sb.AppendLine();

        if (conventions.EntityNamespace is { } ns)
            sb.AppendLine($"- **Entity namespace:** `{ns}`");

        if (conventions.EntityFolder is { } entityFolder)
            sb.AppendLine($"- **Entities live in:** `{entityFolder}/`");

        if (conventions.ControllerFolders.Count > 0)
        {
            sb.AppendLine("- **Controllers live in:** " +
                          string.Join(", ", conventions.ControllerFolders.Select(folder => $"`{folder}/`")));
        }

        if (conventions.DominantEntityBaseType is { } entityBase)
            sb.AppendLine($"- **Entity base class:** `{entityBase}`");

        if (conventions.DominantControllerBaseType is { } controllerBase)
            sb.AppendLine($"- **Controller base class:** `{controllerBase}`");

        sb.AppendLine(conventions.UsesNamedAssociations
            ? "- **Associations** are declared with explicit `[Association(\"Name\")]` names — keep naming them."
            : "- **Associations** are inferred from property types rather than named explicitly.");

        if (conventions.UsesPersistentAlias)
            sb.AppendLine("- **Calculated properties** use `[PersistentAlias]`, evaluated by the database rather than in C#.");

        if (conventions.UsesValidationAttributes)
            sb.AppendLine("- **Validation** is expressed with XAF rule attributes (`[RuleRequiredField]`, `[RuleCriteria]`, …), not manual checks.");

        if (conventions.UsesAppearanceRules)
            sb.AppendLine("- **Conditional UI** uses `[Appearance]` attributes rather than code in controllers.");

        if (project.ModuleInfo is { } module && module.RegisteredTypes.Count > 0)
            sb.AppendLine($"- **{module.RegisteredTypes.Count} types** are explicitly registered in `{module.ModuleClassName}`.");

        sb.AppendLine();

        // Custom attributes are the team's own vocabulary. They exist in no documentation, so an
        // agent that does not read them here will treat them as noise or invent a meaning.
        if (project.CustomAttributes.Count > 0)
        {
            sb.AppendLine("### Attributes this application defines itself");
            sb.AppendLine();
            sb.AppendLine("Not part of XAF or .NET — this team wrote them, so their meaning is in this codebase");
            sb.AppendLine("and nowhere else. Read the definition before assuming what one does:");
            sb.AppendLine();

            foreach (var attribute in project.CustomAttributes)
                sb.AppendLine($"- `[{attribute}]`");

            sb.AppendLine();
        }
    }

    // --------------------------------------------------------------- recipes

    private static void WriteRecipes(
        StringBuilder sb,
        ExtractedProject project,
        CodebaseConventions conventions)
    {
        sb.AppendLine("## Making common changes");
        sb.AppendLine();
        sb.AppendLine("The steps that fit *this* application. They are derived from how existing code is arranged,");
        sb.AppendLine("so following them produces changes that look like they belong.");
        sb.AppendLine();

        // Adding an entity.
        sb.AppendLine("**Add a business entity**");
        sb.AppendLine();
        var step = 1;

        if (conventions.EntityFolder is { } folder && conventions.EntityNamespace is { } entityNs)
            sb.AppendLine($"{step++}. Create the class in `{folder}/`, namespace `{entityNs}`.");
        else
            sb.AppendLine($"{step++}. Create the class alongside the existing business objects.");

        if (conventions.DominantEntityBaseType is { } entityBase)
            sb.AppendLine($"{step++}. Derive from `{entityBase}`, matching the existing entities.");

        sb.AppendLine($"{step++}. Add `[DefaultClassOptions]` if it should appear in navigation on its own.");

        // Not a registration step. XAF finds business classes declared in a module by itself;
        // AdditionalExportedTypes is for types it cannot find, which normally means types from
        // another assembly. This used to read "register the type, as the other 4 are", turning a
        // partial list into an obligation an agent would then perpetuate.
        if (project.ModuleInfo is { } mod && mod.RegisteredTypes.Count > 0)
        {
            sb.AppendLine($"{step++}. No registration needed — XAF picks up business classes declared " +
                          $"in this module. `{mod.ModuleClassName}` exports {mod.RegisteredTypes.Count} " +
                          $"{Plural(mod.RegisteredTypes.Count, "type", "types")} through " +
                          "`AdditionalExportedTypes`, which is only for types XAF cannot find on its own.");
        }

        if (project.SeedData.Count > 0)
            sb.AppendLine($"{step++}. If it needs starting data, extend the module updater — {project.SeedData.Count} seed {Plural(project.SeedData.Count, "method", "methods")} already exist.");

        sb.AppendLine();

        // Adding an action.
        sb.AppendLine("**Add an action**");
        sb.AppendLine();
        step = 1;

        if (conventions.ControllerFolders is [var onlyFolder])
        {
            sb.AppendLine($"{step++}. Put the controller in `{onlyFolder}/`.");
        }
        else if (conventions.ControllerFolders.Count > 1)
        {
            // Which of them is right depends on the action, so say so rather than picking one.
            sb.AppendLine($"{step++}. Put the controller in " +
                          string.Join(" or ", conventions.ControllerFolders.Select(folder => $"`{folder}/`")) +
                          " — the module for anything platform-independent, the platform project only " +
                          "when it touches that platform's UI.");
        }

        if (conventions.DominantControllerBaseType is { } cBase)
            sb.AppendLine($"{step++}. Derive from `{cBase}`.");

        sb.AppendLine($"{step++}. Declare the action as a field, configure it in the constructor, and subscribe to `Execute` there.");
        sb.AppendLine($"{step++}. Set `TargetObjectType` so it only appears on the intended views.");
        sb.AppendLine();

        // Adding validation.
        if (conventions.UsesValidationAttributes)
        {
            sb.AppendLine("**Add a validation rule**");
            sb.AppendLine();
            sb.AppendLine("1. Prefer a rule attribute on the property or class over a manual check in a controller.");
            sb.AppendLine("2. Use the criteria dialect shown above for conditional rules.");
            sb.AppendLine("3. Always supply `CustomMessageTemplate` — the default message names the property, not the business rule.");
            sb.AppendLine();
        }
    }

    private static void WriteDetailPointers(StringBuilder sb, IReadOnlyList<string> detailFiles)
    {
        if (detailFiles.Count == 0)
            return;

        sb.AppendLine("## Detail, on demand");
        sb.AppendLine();
        sb.AppendLine("Deliberately kept out of this file so it does not consume context on every request.");
        sb.AppendLine("**Open these when a question actually needs them** — they contain full property lists,");
        sb.AppendLine("action handler code, validation messages and Model Editor settings:");
        sb.AppendLine();

        foreach (var file in detailFiles.OrderBy(f => f, StringComparer.Ordinal))
            sb.AppendLine($"- `{DetailFolder}/{file}`");

        sb.AppendLine();
    }

    private static void WriteFooter(StringBuilder sb)
    {
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("Generated by [XAF Logic Explainer](https://github.com/peopleworks/XAFLogicExplainer).");
        sb.AppendLine("It describes this application only. For how the XAF framework itself works, use the");
        sb.AppendLine("[DevExpress agent skills](https://github.com/DevExpress/agent-skills) and the DevExpress");
        sb.AppendLine("documentation MCP server, which are complementary to this file.");
    }

    // --------------------------------------------------------------- helpers

    private static string PropertyMarkers(ExtractedProperty property)
    {
        var markers = new StringBuilder();
        if (property.IsKey) markers.Append('#');
        if (property.IsRequired) markers.Append('*');
        if (property.IsComputed) markers.Append('=');
        return markers.ToString();
    }

    private static string RelationshipArrow(RelationshipType type) => type switch
    {
        RelationshipType.OneToMany => "many",
        RelationshipType.ManyToOne => "one",
        RelationshipType.ManyToMany => "many↔many",
        _ => "→",
    };

    private static string ShortActionType(string? actionType)
    {
        if (string.IsNullOrWhiteSpace(actionType))
            return "action";

        // "SimpleAction" reads better than "SimpleAction" spelled out with its namespace, and the
        // table has no room for the latter.
        var name = actionType.Contains('.')
            ? actionType[(actionType.LastIndexOf('.') + 1)..]
            : actionType;

        return name.EndsWith("Action", StringComparison.Ordinal)
            ? name[..^"Action".Length]
            : name;
    }

    /// <summary>
    /// Makes a value safe inside a markdown table cell.
    /// </summary>
    /// <remarks>
    /// Criteria strings and default values contain pipes often enough that an unescaped one
    /// silently corrupts the table for every reader after it.
    /// </remarks>
    private static string Cell(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "—";

        return value
            .Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal)
            .Trim();
    }

    private static string Truncate(string value, int max) =>
        value.Length <= max ? value : value[..max] + " …";

    private static string Short(string? hash) =>
        string.IsNullOrWhiteSpace(hash) ? "(none)" : hash[..Math.Min(12, hash.Length)];

    private static string Plural(int count, string singular, string plural) =>
        count == 1 ? singular : plural;
}
