using System.Text;
using XafLogicExplainer.Core.Interfaces;
using XafLogicExplainer.Core.Models;

namespace XafLogicExplainer.Core.Generators;

/// <summary>
/// Builds the always-loaded index that teaches an AI coding agent about one specific XAF application.
/// </summary>
/// <remarks>
/// <para>
/// This is deliberately not the full documentation. An <c>AGENTS.md</c> is prepended to every
/// conversation an agent has in the repository, so its cost is paid on every request forever.
/// Sixty thousand characters of entity detail there would crowd out the user's actual question and
/// bury the few facts that change an answer.
/// </para>
/// <para>
/// So the output is tiered. This file produces a compact map: what the application is, what
/// definitively exists in it, the conventions it follows, and where the detail lives. The detail
/// itself goes to separate files the agent opens only when a question needs them.
/// </para>
/// <para>
/// The highest-value section is <em>Ground rules</em>, and specifically the closed-world statement.
/// Telling an agent that an inventory is complete converts "I did not find it" into "it does not
/// exist", which is the single most effective thing a document can do to stop invention.
/// </para>
/// <para>
/// Scaffolding text is English regardless of the <c>--lang</c> setting: these are instructions
/// addressed to a model, and English is where instruction-following is most reliable. The content
/// woven into them — entity names, captions, descriptions — stays in whatever language the
/// codebase is written in.
/// </para>
/// </remarks>
public sealed class AgentContextGenerator
{
    /// <summary>Longest criteria expression reproduced verbatim in the index.</summary>
    private const int MaxCriteriaLength = 160;

    /// <summary>How many criteria examples earn a place in the always-loaded tier.</summary>
    private const int MaxCriteriaExamples = 12;

    /// <summary>Directory, relative to the output root, holding the on-demand detail files.</summary>
    public const string DetailFolder = ".xaflogic";

    private readonly string _toolVersion;

    /// <summary>
    /// Creates a generator.
    /// </summary>
    /// <param name="toolVersion">Version stamped into the provenance header.</param>
    public AgentContextGenerator(string toolVersion = "0.9.0")
    {
        _toolVersion = toolVersion;
    }

    /// <summary>
    /// Generates the body of <c>AGENTS.md</c>.
    /// </summary>
    /// <param name="project">The extracted application.</param>
    /// <param name="detailFiles">
    /// File names written into <see cref="DetailFolder"/>, so the index can point at them.
    /// </param>
    public string GenerateIndex(ExtractedProject project, IReadOnlyList<string> detailFiles)
    {
        var conventions = CodebaseConventions.Infer(project);
        var sb = new StringBuilder();

        WriteHeader(sb, project);
        WriteSummary(sb, project);
        WriteGroundRules(sb, project, conventions);
        WriteEntityInventory(sb, project);
        WriteOperationsInventory(sb, project);
        WriteNavigation(sb, project);
        WriteCriteriaExamples(sb, conventions);
        WriteConventions(sb, project, conventions);
        WriteRecipes(sb, project, conventions);
        WriteDetailPointers(sb, detailFiles);
        WriteFooter(sb);

        return sb.ToString();
    }

    /// <summary>
    /// Generates the ground-rules block on its own.
    /// </summary>
    /// <remarks>
    /// GitHub Copilot's instructions file has no import mechanism, so it cannot point at
    /// <c>AGENTS.md</c> the way Claude Code can. This block is small enough to inline there and
    /// carries most of the anti-hallucination value on its own.
    /// </remarks>
    public string GenerateGroundRules(ExtractedProject project)
    {
        var sb = new StringBuilder();
        WriteGroundRules(
            sb,
            project,
            CodebaseConventions.Infer(project),
            asSection: false,
            // Copilot's instructions file carries the rules but not the tables, so pointing at
            // "this file" would send the reader looking for inventories that are not there.
            inventoryLocation: "in `AGENTS.md`");
        return sb.ToString();
    }

    // ---------------------------------------------------------------- header

    private void WriteHeader(StringBuilder sb, ExtractedProject project)
    {
        sb.AppendLine($"# {project.ProjectName} — application context for AI agents");
        sb.AppendLine();
        sb.AppendLine("<!--");
        sb.AppendLine($"  Generated by XAF Logic Explainer {_toolVersion} on {project.ExtractedAt}");
        sb.AppendLine($"  Source fingerprint: {Short(project.SourceHash)}");
        sb.AppendLine();
        sb.AppendLine("  This file is generated from source. Edits are overwritten.");
        sb.AppendLine("  Refresh it with:  xaflogic agents --project <module path>");
        sb.AppendLine("-->");
        sb.AppendLine();
    }

    private static void WriteSummary(StringBuilder sb, ExtractedProject project)
    {
        var actionCount = project.Controllers.Sum(c => c.Actions.Count);
        var orm = OrmDisplayName(project.OrmType);

        sb.Append($"A DevExpress XAF application: **{project.Entities.Count} business ");
        sb.Append(Plural(project.Entities.Count, "entity", "entities"));
        sb.Append($"**, **{project.Controllers.Count} {Plural(project.Controllers.Count, "controller", "controllers")}**");

        if (actionCount > 0)
            sb.Append($" exposing **{actionCount} {Plural(actionCount, "action", "actions")}**");

        sb.Append($", persisted with **{orm}**");

        if (!string.IsNullOrWhiteSpace(project.TargetFramework))
            sb.Append($", targeting **{project.TargetFramework}**");

        sb.AppendLine(".");
        sb.AppendLine();

        if (project.ModuleInfo is { } module && !string.IsNullOrWhiteSpace(module.ModuleClassName))
        {
            sb.AppendLine($"The XAF module class is `{module.ModuleClassName}`.");

            if (module.RequiredModules.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("Required XAF modules:");
                sb.AppendLine();
                foreach (var required in module.RequiredModules.OrderBy(m => m, StringComparer.Ordinal))
                    sb.AppendLine($"- `{required}`");
            }

            sb.AppendLine();
        }
    }

    // ----------------------------------------------------------- ground rules

    private static void WriteGroundRules(
        StringBuilder sb,
        ExtractedProject project,
        CodebaseConventions conventions,
        bool asSection = true,
        string inventoryLocation = "in this file")
    {
        if (asSection)
        {
            sb.AppendLine("## Ground rules");
            sb.AppendLine();
            sb.AppendLine("These constrain every answer about this codebase.");
            sb.AppendLine();
        }

        var isEfCore = IsEfCore(project.OrmType);
        var rule = 1;

        // Rule 1: the ORM. Mixing XPO and EF Core idioms is the most frequent way generated XAF
        // code turns out wrong, because both are legitimate XAF and the class names collide --
        // BaseObject exists in both, in different namespaces.
        if (isEfCore)
        {
            sb.AppendLine($"**{rule++}. Persistence is Entity Framework Core, not XPO.**");
            sb.AppendLine("`Session`, `XPObject`, `XPCollection`, `UnitOfWork` and `XPO` criteria APIs do not exist");
            sb.AppendLine("in this application and must never be suggested. Entities are mapped through a");
            sb.AppendLine("`DbContext`, and XAF reaches them through `IObjectSpace`");
            sb.AppendLine("(`GetObjects<T>()`, `CreateObject<T>()`, `CommitChanges()`).");
        }
        else
        {
            sb.AppendLine($"**{rule++}. Persistence is DevExpress XPO, not Entity Framework.**");
            sb.AppendLine("`DbContext`, `DbSet<T>`, `OnModelCreating`, EF migrations and EF-style data annotations");
            sb.AppendLine("do not exist in this application and must never be suggested. Collections are");
            sb.AppendLine("`XPCollection<T>`, and data access goes through `IObjectSpace`");
            sb.AppendLine("(`GetObjects<T>()`, `CreateObject<T>()`, `CommitChanges()`) or a `Session`.");
        }

        sb.AppendLine();

        // Rule 2: the closed-world statement. This is the load-bearing one.
        sb.AppendLine($"**{rule++}. The inventories {inventoryLocation} are complete.**");
        sb.AppendLine("They were extracted from the whole source tree, not sampled. If an entity, controller or");
        sb.AppendLine("action does not appear there, it does not exist in this application — say so plainly rather");
        sb.AppendLine("than assuming it lives in a file you have not opened. When a request needs something that");
        sb.AppendLine("is genuinely absent, the honest answer is that it must be created.");
        sb.AppendLine();

        // Rule 3: local conventions beat tutorials.
        if (conventions.DominantEntityBaseType is { } baseType)
        {
            sb.AppendLine($"**{rule++}. Follow this codebase, not generic XAF tutorials.**");
            sb.AppendLine($"Persistent classes here derive from `{baseType}`, and the *Conventions* section below");
            sb.AppendLine("records how this team writes associations, calculated properties and validation. Match");
            sb.AppendLine("what is already here; XAF usually offers several ways to express the same idea, and the");
            sb.AppendLine("one already in use is the correct one.");
            sb.AppendLine();
        }

        // Rule 4: the Model Editor -- invisible customizations that make C#-only reading wrong.
        if (conventions.HasModelEditorCustomizations)
        {
            sb.AppendLine($"**{rule++}. Some behavior lives in the Model Editor, not in C#.**");
            sb.AppendLine("This application has `.xafml` customizations: captions, list columns, filters and view");
            sb.AppendLine("settings that override what the C# suggests. Before concluding how a screen behaves from");
            sb.AppendLine($"the business classes alone, check the Model Editor detail in `{DetailFolder}/`.");
            sb.AppendLine();
        }

        // Rule 5: staleness. Generated context that quietly goes out of date is worse than none.
        sb.AppendLine($"**{rule}. This file can go stale.**");
        sb.AppendLine("It reflects the source as of the timestamp in the header. If the code you are reading");
        sb.AppendLine("disagrees with this file, the code is right — and the file should be regenerated with");
        sb.AppendLine("`xaflogic agents`.");
        sb.AppendLine();
    }

    // ------------------------------------------------------------ inventories

    private static void WriteEntityInventory(StringBuilder sb, ExtractedProject project)
    {
        if (project.Entities.Count == 0)
            return;

        sb.AppendLine($"## Business entities ({project.Entities.Count} — complete)");
        sb.AppendLine();
        sb.AppendLine("| Entity | Base | Notable properties | Relationships |");
        sb.AppendLine("| --- | --- | --- | --- |");

        foreach (var entity in project.Entities.OrderBy(e => e.ClassName, StringComparer.Ordinal))
        {
            var notable = entity.Properties
                .Where(p => !p.IsCollection)
                .OrderByDescending(p => p.IsKey)
                .ThenByDescending(p => p.IsRequired)
                .ThenByDescending(p => p.IsComputed)
                .Take(5)
                .Select(p => $"`{p.Name}`{PropertyMarkers(p)}");

            var relationships = entity.Relationships
                .Take(4)
                .Select(r => $"{RelationshipArrow(r.Type)} `{r.RelatedEntity}`{(r.IsAggregated ? " (owned)" : "")}");

            var more = entity.Relationships.Count > 4 ? $" +{entity.Relationships.Count - 4}" : "";

            sb.Append($"| **{entity.ClassName}** ");
            sb.Append($"| `{Cell(entity.BaseType)}` ");
            sb.Append($"| {Cell(string.Join(", ", notable))} ");
            sb.AppendLine($"| {Cell(string.Join(", ", relationships) + more)} |");
        }

        sb.AppendLine();
        sb.AppendLine("Markers: `*` required · `=` calculated · `#` key.");
        sb.AppendLine();
    }

    private static void WriteOperationsInventory(StringBuilder sb, ExtractedProject project)
    {
        var withActions = project.Controllers.Where(c => c.Actions.Count > 0).ToList();
        var actionCount = withActions.Sum(c => c.Actions.Count);

        sb.AppendLine($"## Business operations ({actionCount} {Plural(actionCount, "action", "actions")} — complete)");
        sb.AppendLine();

        if (actionCount == 0)
        {
            sb.AppendLine("This application defines no custom actions. Its controllers, if any, customize behavior");
            sb.AppendLine("without adding commands to the UI.");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("| Action | Type | Controller | Applies to |");
            sb.AppendLine("| --- | --- | --- | --- |");

            foreach (var controller in withActions.OrderBy(c => c.ClassName, StringComparer.Ordinal))
            {
                foreach (var action in controller.Actions)
                {
                    var caption = string.IsNullOrWhiteSpace(action.Caption) ? action.ActionId : action.Caption;
                    var target = controller.TargetObjectType ?? "any view";

                    sb.Append($"| **{Cell(caption)}** ");
                    sb.Append($"| {Cell(ShortActionType(action.ActionType))} ");
                    sb.Append($"| `{Cell(controller.ClassName)}` ");
                    sb.AppendLine($"| {Cell(target)} |");
                }
            }

            sb.AppendLine();
            sb.AppendLine($"What each action *does* — including its handler code — is in `{DetailFolder}/`.");
            sb.AppendLine();
        }

        // Controllers without actions still matter: they change behavior invisibly, and an agent
        // that only reads the action table would conclude they do nothing.
        var silent = project.Controllers.Where(c => c.Actions.Count == 0).ToList();
        if (silent.Count > 0)
        {
            sb.AppendLine($"{silent.Count} further {Plural(silent.Count, "controller", "controllers")} define no actions but still");
            sb.AppendLine("customize behavior (view events, defaults, filtering):");
            sb.AppendLine();
            foreach (var controller in silent.OrderBy(c => c.ClassName, StringComparer.Ordinal))
            {
                var target = string.IsNullOrWhiteSpace(controller.TargetObjectType)
                    ? ""
                    : $" — targets `{controller.TargetObjectType}`";
                sb.AppendLine($"- `{controller.ClassName}`{target}");
            }
            sb.AppendLine();
        }
    }

    private static void WriteNavigation(StringBuilder sb, ExtractedProject project)
    {
        if (project.Navigation.Count == 0)
            return;

        sb.AppendLine("## Navigation");
        sb.AppendLine();
        sb.AppendLine("What a user sees in the menu, which is usually how they will describe a screen to you:");
        sb.AppendLine();

        foreach (var group in project.Navigation)
        {
            sb.AppendLine($"- **{group.GroupName}** — {string.Join(", ", group.EntityClassNames.Select(e => $"`{e}`"))}");
        }

        sb.AppendLine();
    }

    private static void WriteCriteriaExamples(StringBuilder sb, CodebaseConventions conventions)
    {
        if (conventions.CriteriaExamples.Count == 0)
            return;

        sb.AppendLine("## Criteria expressions used here");
        sb.AppendLine();
        sb.AppendLine("XAF filters, validates and styles with criteria strings, which are neither SQL nor C#.");
        sb.AppendLine("These are real expressions from this codebase — follow their dialect:");
        sb.AppendLine();
        sb.AppendLine("```");

        foreach (var example in conventions.CriteriaExamples.Take(MaxCriteriaExamples))
        {
            sb.AppendLine($"// {example.Context}");
            sb.AppendLine(Truncate(example.Expression, MaxCriteriaLength));
            sb.AppendLine();
        }

        sb.AppendLine("```");
        sb.AppendLine();

        if (conventions.CriteriaExamples.Count > MaxCriteriaExamples)
        {
            var remaining = conventions.CriteriaExamples.Count - MaxCriteriaExamples;
            sb.AppendLine($"({remaining} further {Plural(remaining, "expression", "expressions")} in `{DetailFolder}/`.)");
            sb.AppendLine();
        }
    }

    private static void WriteConventions(
        StringBuilder sb,
        ExtractedProject project,
        CodebaseConventions conventions)
    {
        sb.AppendLine("## Conventions observed in this codebase");
        sb.AppendLine();
        sb.AppendLine("Inferred from the source, not from XAF documentation. New code should match these.");
        sb.AppendLine();

        if (conventions.EntityNamespace is { } ns)
            sb.AppendLine($"- **Entity namespace:** `{ns}`");

        if (conventions.EntityFolder is { } entityFolder)
            sb.AppendLine($"- **Entities live in:** `{entityFolder}/`");

        if (conventions.ControllerFolder is { } controllerFolder)
            sb.AppendLine($"- **Controllers live in:** `{controllerFolder}/`");

        if (conventions.DominantEntityBaseType is { } entityBase)
            sb.AppendLine($"- **Entity base class:** `{entityBase}`");

        if (conventions.DominantControllerBaseType is { } controllerBase)
            sb.AppendLine($"- **Controller base class:** `{controllerBase}`");

        sb.AppendLine(conventions.UsesNamedAssociations
            ? "- **Associations** are declared with explicit `[Association(\"Name\")]` names — keep naming them."
            : "- **Associations** are inferred from property types rather than named explicitly.");

        if (conventions.UsesPersistentAlias)
            sb.AppendLine("- **Calculated properties** use `[PersistentAlias]`, evaluated by the database rather than in C#.");

        if (conventions.UsesValidationAttributes)
            sb.AppendLine("- **Validation** is expressed with XAF rule attributes (`[RuleRequiredField]`, `[RuleCriteria]`, …), not manual checks.");

        if (conventions.UsesAppearanceRules)
            sb.AppendLine("- **Conditional UI** uses `[Appearance]` attributes rather than code in controllers.");

        if (project.ModuleInfo is { } module && module.RegisteredTypes.Count > 0)
            sb.AppendLine($"- **{module.RegisteredTypes.Count} types** are explicitly registered in `{module.ModuleClassName}`.");

        sb.AppendLine();
    }

    // --------------------------------------------------------------- recipes

    private static void WriteRecipes(
        StringBuilder sb,
        ExtractedProject project,
        CodebaseConventions conventions)
    {
        sb.AppendLine("## Making common changes");
        sb.AppendLine();
        sb.AppendLine("The steps that fit *this* application. They are derived from how existing code is arranged,");
        sb.AppendLine("so following them produces changes that look like they belong.");
        sb.AppendLine();

        // Adding an entity.
        sb.AppendLine("**Add a business entity**");
        sb.AppendLine();
        var step = 1;

        if (conventions.EntityFolder is { } folder && conventions.EntityNamespace is { } entityNs)
            sb.AppendLine($"{step++}. Create the class in `{folder}/`, namespace `{entityNs}`.");
        else
            sb.AppendLine($"{step++}. Create the class alongside the existing business objects.");

        if (conventions.DominantEntityBaseType is { } entityBase)
            sb.AppendLine($"{step++}. Derive from `{entityBase}`, matching the existing entities.");

        sb.AppendLine($"{step++}. Add `[DefaultClassOptions]` if it should appear in navigation on its own.");

        if (project.ModuleInfo is { } mod && mod.RegisteredTypes.Count > 0)
            sb.AppendLine($"{step++}. Register the type in `{mod.ModuleClassName}`, as the other {mod.RegisteredTypes.Count} are.");

        if (project.SeedData.Count > 0)
            sb.AppendLine($"{step++}. If it needs starting data, extend the module updater — {project.SeedData.Count} seed {Plural(project.SeedData.Count, "method", "methods")} already exist.");

        sb.AppendLine();

        // Adding an action.
        sb.AppendLine("**Add an action**");
        sb.AppendLine();
        step = 1;

        if (conventions.ControllerFolder is { } cFolder)
            sb.AppendLine($"{step++}. Put the controller in `{cFolder}/`.");

        if (conventions.DominantControllerBaseType is { } cBase)
            sb.AppendLine($"{step++}. Derive from `{cBase}`.");

        sb.AppendLine($"{step++}. Declare the action as a field, configure it in the constructor, and subscribe to `Execute` there.");
        sb.AppendLine($"{step++}. Set `TargetObjectType` so it only appears on the intended views.");
        sb.AppendLine();

        // Adding validation.
        if (conventions.UsesValidationAttributes)
        {
            sb.AppendLine("**Add a validation rule**");
            sb.AppendLine();
            sb.AppendLine("1. Prefer a rule attribute on the property or class over a manual check in a controller.");
            sb.AppendLine("2. Use the criteria dialect shown above for conditional rules.");
            sb.AppendLine("3. Always supply `CustomMessageTemplate` — the default message names the property, not the business rule.");
            sb.AppendLine();
        }
    }

    private static void WriteDetailPointers(StringBuilder sb, IReadOnlyList<string> detailFiles)
    {
        if (detailFiles.Count == 0)
            return;

        sb.AppendLine("## Detail, on demand");
        sb.AppendLine();
        sb.AppendLine("Deliberately kept out of this file so it does not consume context on every request.");
        sb.AppendLine("**Open these when a question actually needs them** — they contain full property lists,");
        sb.AppendLine("action handler code, validation messages and Model Editor settings:");
        sb.AppendLine();

        foreach (var file in detailFiles.OrderBy(f => f, StringComparer.Ordinal))
            sb.AppendLine($"- `{DetailFolder}/{file}`");

        sb.AppendLine();
    }

    private static void WriteFooter(StringBuilder sb)
    {
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("Generated by [XAF Logic Explainer](https://github.com/peopleworks/XAFLogicExplainer).");
        sb.AppendLine("It describes this application only. For how the XAF framework itself works, use the");
        sb.AppendLine("[DevExpress agent skills](https://github.com/DevExpress/agent-skills) and the DevExpress");
        sb.AppendLine("documentation MCP server, which are complementary to this file.");
    }

    // --------------------------------------------------------------- helpers

    private static bool IsEfCore(string? ormType) =>
        ormType is not null && ormType.Contains("EF", StringComparison.OrdinalIgnoreCase);

    private static string OrmDisplayName(string? ormType) =>
        IsEfCore(ormType) ? "Entity Framework Core" : "XPO";

    private static string PropertyMarkers(ExtractedProperty property)
    {
        var markers = new StringBuilder();
        if (property.IsKey) markers.Append('#');
        if (property.IsRequired) markers.Append('*');
        if (property.IsComputed) markers.Append('=');
        return markers.ToString();
    }

    private static string RelationshipArrow(RelationshipType type) => type switch
    {
        RelationshipType.OneToMany => "many",
        RelationshipType.ManyToOne => "one",
        RelationshipType.ManyToMany => "many↔many",
        _ => "→",
    };

    private static string ShortActionType(string? actionType)
    {
        if (string.IsNullOrWhiteSpace(actionType))
            return "action";

        // "SimpleAction" reads better than "SimpleAction" spelled out with its namespace, and the
        // table has no room for the latter.
        var name = actionType.Contains('.')
            ? actionType[(actionType.LastIndexOf('.') + 1)..]
            : actionType;

        return name.EndsWith("Action", StringComparison.Ordinal)
            ? name[..^"Action".Length]
            : name;
    }

    /// <summary>
    /// Makes a value safe inside a markdown table cell.
    /// </summary>
    /// <remarks>
    /// Criteria strings and default values contain pipes often enough that an unescaped one
    /// silently corrupts the table for every reader after it.
    /// </remarks>
    private static string Cell(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "—";

        return value
            .Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal)
            .Trim();
    }

    private static string Truncate(string value, int max) =>
        value.Length <= max ? value : value[..max] + " …";

    private static string Short(string? hash) =>
        string.IsNullOrWhiteSpace(hash) ? "(none)" : hash[..Math.Min(12, hash.Length)];

    private static string Plural(int count, string singular, string plural) =>
        count == 1 ? singular : plural;
}
