using System.Text;
using System.Text.Json;
using XafLogicExplainer.Core.Interfaces;
using XafLogicExplainer.Core.Models;

namespace XafLogicExplainer.Core.Generators;

/// <summary>
/// Generates markdown and JSON documentation artifacts from extracted project metadata.
/// </summary>
public class MarkdownDocumentationGenerator : IDocumentationGenerator
{
    private readonly DocumentationLabels _l;
    private readonly bool _spanish;

    /// <summary>
    /// Creates a documentation generator for the selected language.
    /// </summary>
    /// <param name="languageCode">Language code used for labels and section captions.</param>
    public MarkdownDocumentationGenerator(string languageCode = "es")
    {
        _l = DocumentationLabels.ForLanguage(languageCode);
        _spanish = languageCode.StartsWith("es", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Picks the wording for the current language.
    /// </summary>
    /// <remarks>
    /// For prose that belongs to one section, where a label on <see cref="DocumentationLabels"/>
    /// would be a caption used once.
    /// </remarks>
    /// <param name="es">Spanish text.</param>
    /// <param name="en">English text.</param>
    private string L(string es, string en) => _spanish ? es : en;

    /// <summary>
    /// Generates a full combined markdown document.
    /// </summary>
    /// <param name="project">Extracted project snapshot.</param>
    /// <returns>Full markdown document.</returns>
    public string GenerateMarkdown(ExtractedProject project)
    {
        var sections = GenerateSections(project);
        var sb = new StringBuilder();

        sb.AppendLine($"# {project.ProjectName} - {_l.FunctionalDocumentation}");
        sb.AppendLine();
        sb.AppendLine($"*Generated: {project.ExtractedAt}*");
        sb.AppendLine($"*Framework: {project.TargetFramework}*");
        sb.AppendLine();

        foreach (var section in sections)
        {
            sb.AppendLine(section.Content);
            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>
    /// Serializes project extraction output as JSON.
    /// </summary>
    /// <param name="project">Extracted project snapshot.</param>
    /// <returns>JSON representation of the project.</returns>
    public string GenerateJson(ExtractedProject project)
    {
        return JsonSerializer.Serialize(project, JsonOptions);
    }

    /// <summary>
    /// Deserializes an extracted project from JSON.
    /// </summary>
    /// <param name="json">JSON payload generated by this toolchain.</param>
    /// <returns>Deserialized project model or null when payload is invalid.</returns>
    public static ExtractedProject? DeserializeProject(string json)
    {
        return JsonSerializer.Deserialize<ExtractedProject>(json, JsonOptions);
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    /// <summary>
    /// Generates all standalone documentation sections for upload or local export.
    /// </summary>
    /// <param name="project">Extracted project snapshot.</param>
    /// <returns>List of generated sections.</returns>
    public List<DocumentSection> GenerateSections(ExtractedProject project)
    {
        var sections = new List<DocumentSection>
        {
            GenerateOverviewSection(project),
            GenerateEntitiesSection(project),
            GenerateControllersSection(project),
            GenerateBusinessRulesSection(project),
            GenerateConfigurationSection(project),
            GenerateNavigationSection(project),
        };

        if (project.ModelEditorInfo != null)
            sections.Add(GenerateModelEditorSection(project));

        if (project.Views.Count > 0)
            sections.Add(GenerateScreensSection(project));

        return sections;
    }

    /// <summary>Joins controller names for a one-line mention.</summary>
    private static string Names(IEnumerable<ViewActivation> activations) =>
        string.Join(", ", activations
            .OrderBy(a => a.Controller, StringComparer.Ordinal)
            .Select(a => $"`{a.Controller}`"));

    /// <summary>
    /// Says in one phrase what kind of view this is, where it appears, and where it came from.
    /// </summary>
    /// <remarks>
    /// Written out rather than printed as three enum names, which would leave English words inside
    /// the Spanish document. The view class names stay as they are: <c>DetailView</c> is what XAF
    /// calls it, in either language.
    /// </remarks>
    private string DescribeView(ExtractedView view)
    {
        var kind = view.ViewType switch
        {
            ModelViewType.ListView when view.Id.EndsWith("_LookupListView", StringComparison.Ordinal) =>
                L("Vista de busqueda", "Lookup list view"),
            ModelViewType.ListView => L("Vista de lista", "List view"),
            ModelViewType.DetailView => L("Vista de detalle", "Detail view"),
            _ => L("Dashboard", "Dashboard"),
        };

        var where = view.Nesting switch
        {
            ViewNesting.Root => L("raiz", "root"),
            ViewNesting.Nested => L("anidada", "nested"),
            _ => L("raiz o anidada", "root or nested"),
        };

        var origin = view.Origin switch
        {
            ViewOrigin.Generated => L("generada por XAF, no existe en ningun archivo",
                                      "generated by XAF, exists in no file"),
            ViewOrigin.Customized => L("generada por XAF y personalizada en el Model Editor",
                                       "generated by XAF and customized in the Model Editor"),
            _ => L("definida en el Model Editor", "defined in the Model Editor"),
        };

        return $"{kind}, {where}, {origin}";
    }

    /// <summary>
    /// Generates the screen inventory: every view, and what XAF loads onto it.
    /// </summary>
    /// <remarks>
    /// Kept out of the always-loaded index on purpose — an application of any size has hundreds of
    /// views, and this is the file to open when the question is about one screen.
    /// </remarks>
    private DocumentSection GenerateScreensSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.Screens}");
        sb.AppendLine();
        sb.AppendLine(L(
            $"{project.Views.Count} vistas. XAF genera una vista de lista, una de detalle y una de busqueda " +
            "por cada clase de negocio, mas una lista por cada coleccion, asi que la mayoria no existe en " +
            "ningun archivo: buscarlas en el codigo no encuentra nada, y eso no significa que falten.",
            $"{project.Views.Count} views. XAF generates a list, a detail and a lookup view for every " +
            "business class, plus a list view for every collection, so most of these exist in no file: " +
            "searching the source tree for one finds nothing, and that is not evidence it is missing."));

        foreach (var group in project.Views
                     .GroupBy(v => v.ObjectType ?? "-")
                     .OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            sb.AppendLine();
            sb.AppendLine($"## {group.Key}");
            sb.AppendLine();

            foreach (var view in group.OrderBy(v => v.Id, StringComparer.Ordinal))
            {
                sb.AppendLine($"### {view.Id}");
                sb.AppendLine();
                sb.AppendLine($"- {DescribeView(view)}");

                if (view.InNavigation)
                    sb.AppendLine(L("- Abierta desde la navegacion", "- Opened from navigation"));

                if (view.OwnerProperty is { } ownerProperty)
                    sb.AppendLine($"- {L("Mostrada por", "Shown by")} `{view.OwnerEntity}.{ownerProperty}`");

                var mine = view.Activates.Where(a => !a.Framework).ToList();
                var framework = view.Activates.Where(a => a.Framework).ToList();

                if (mine.Count == 0)
                {
                    sb.AppendLine(L(
                        "- Ningun controlador de esta aplicacion se activa aqui.",
                        "- No controller of this application activates here."));
                }

                foreach (var activation in mine)
                {
                    sb.Append($"- `{activation.Controller}` — ");
                    sb.AppendLine(activation.Reasons.Count == 0
                        ? L("no restringe nada, corre en todas las vistas",
                            "restricts nothing, runs on every view")
                        : string.Join(L(", y ", ", and "), activation.Reasons
                            .Select(reason => ActivationReasonText.ForLanguage(reason, _spanish))));

                    foreach (var action in activation.Actions)
                        sb.AppendLine($"  - {action}");
                }

                // Named but not expanded: inherited behaviour, and a lot of it. Giving each entry
                // the weight of the team's own would bury the line worth reading.
                if (framework.Count > 0)
                {
                    sb.AppendLine(L(
                        $"- Ademas, de XAF: {Names(framework)}",
                        $"- Plus, from XAF: {Names(framework)}"));
                }

                sb.AppendLine();
            }
        }

        if (project.FrameworkAlwaysActive.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine($"## {L("Controladores de XAF en todas las pantallas", "XAF controllers on every screen")}");
            sb.AppendLine();
            sb.AppendLine(L(
                $"Estos no restringen nada, asi que se cargan en las {project.Views.Count} pantallas de " +
                "arriba. Listados una vez y no en cada una.",
                $"These restrict nothing, so they load onto all {project.Views.Count} screens above. " +
                "Listed once rather than under each."));
            sb.AppendLine();
            sb.AppendLine(string.Join(", ", project.FrameworkAlwaysActive.Select(name => $"`{name}`")));
        }
        else if (project.CatalogVersion is null)
        {
            sb.AppendLine();
            sb.AppendLine(L(
                "> Los controladores propios de XAF tambien corren en estas pantallas. Nombrarlos " +
                "necesita el catalogo: `xaflogic catalog build` en una maquina con licencia DevExpress.",
                "> XAF's own controllers run on these screens too. Naming them needs the catalog: " +
                "`xaflogic catalog build` on a machine with a DevExpress licence."));
        }

        sb.AppendLine();
        sb.AppendLine(L(
            "> Un controlador listado aqui todavia puede apagarse solo en tiempo de ejecucion con " +
            "`Active[\"razon\"]`, que depende de los datos y del usuario. Esto es lo que XAF **carga** " +
            "en la pantalla, no lo que necesariamente hara algo.",
            "> A controller listed here can still switch itself off at run time through " +
            "`Active[\"reason\"]`, which depends on the data and the user. This is what XAF **loads** " +
            "onto the screen, not what will necessarily do something."));

        return new DocumentSection
        {
            Title = _l.Screens,
            FileName = $"{project.ProjectName}_Screens",
            Content = sb.ToString(),
            Description = string.Format(_l.ScreensDescription, project.ProjectName),
            Tags = "views,screens,controllers,activation,ui"
        };
    }

    /// <summary>
    /// Generates the overview section with system summary and relationships.
    /// </summary>
    private DocumentSection GenerateOverviewSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.SystemOverview}");
        sb.AppendLine();
        sb.AppendLine($"## {_l.Summary}");
        sb.AppendLine();
        sb.AppendLine($"- **{_l.Project}:** {project.ProjectName}");
        sb.AppendLine($"- **{_l.Framework}:** {project.TargetFramework}");
        sb.AppendLine($"- **ORM:** {project.OrmType}");
        sb.AppendLine($"- **{_l.BusinessEntitiesCount}:** {project.Entities.Count}");
        sb.AppendLine($"- **{_l.ControllersCount}:** {project.Controllers.Count}");
        sb.AppendLine($"- **{_l.NavigationGroups}:** {project.Navigation.Count}");
        if (project.ModelEditorInfo != null)
        {
            sb.AppendLine($"- **{_l.CustomViewsModelEditor}:** {project.ModelEditorInfo.Views.Count}");
            if (project.ModelEditorInfo.Options != null)
            {
                var opts = project.ModelEditorInfo.Options;
                var uiParts = new List<string>();
                if (opts.FormStyle != null) uiParts.Add(opts.FormStyle);
                if (opts.UIType != null) uiParts.Add(opts.UIType);
                if (opts.Skin != null) uiParts.Add(opts.Skin);
                if (uiParts.Count > 0)
                    sb.AppendLine($"- **{_l.UIStyle}:** {string.Join(", ", uiParts)}");
            }
        }
        sb.AppendLine();

        if (project.PackageReferences.Count > 0)
        {
            sb.AppendLine($"## {_l.MainPackages}");
            sb.AppendLine();
            foreach (var pkg in project.PackageReferences.Where(p =>
                         p.Contains("DevExpress") || p.Contains("ExpressApp")))
            {
                sb.AppendLine($"- {pkg}");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"## {_l.NavigationStructure}");
        sb.AppendLine();
        foreach (var nav in project.Navigation)
        {
            sb.AppendLine($"### {nav.GroupName}");
            foreach (var entity in nav.EntityClassNames)
            {
                var entityInfo = project.Entities.FirstOrDefault(e => e.ClassName == entity);
                var desc = entityInfo?.Description ?? "";
                sb.AppendLine($"- **{entity}** {(string.IsNullOrEmpty(desc) ? "" : $"- {desc}")}");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"## {_l.EntityRelationshipMap}");
        sb.AppendLine();
        foreach (var entity in project.Entities.Where(e => e.Relationships.Count > 0))
        {
            foreach (var rel in entity.Relationships)
            {
                var relSymbol = rel.Type == RelationshipType.OneToMany ? "1:N" : "N:1";
                var aggLabel = rel.IsAggregated ? $" ({_l.Composition})" : "";
                sb.AppendLine($"- **{entity.ClassName}** --[{relSymbol}]--> **{rel.RelatedEntity}** via `{rel.PropertyName}`{aggLabel}");
            }
        }

        return new DocumentSection
        {
            Title = _l.SystemOverview,
            FileName = $"{project.ProjectName}_Overview",
            Content = sb.ToString(),
            Description = string.Format(_l.OverviewDescription, project.ProjectName),
            Tags = "overview,navigation,relationships,structure"
        };
    }

    /// <summary>
    /// Generates the business entities section.
    /// </summary>
    private DocumentSection GenerateEntitiesSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.BusinessEntities}");
        sb.AppendLine();

        foreach (var entity in project.Entities.OrderBy(e => e.NavigationGroup ?? "ZZZ").ThenBy(e => e.ClassName))
        {
            sb.AppendLine($"## {entity.ClassName}");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(entity.Description))
                sb.AppendLine($"*{entity.Description}*");

            sb.AppendLine();
            sb.AppendLine($"- **{_l.BaseType}:** {entity.BaseType}");
            if (!string.IsNullOrEmpty(entity.ModelCaption))
                sb.AppendLine($"- **{_l.CaptionModelEditor}:** {entity.ModelCaption}");
            if (!string.IsNullOrEmpty(entity.NavigationGroup))
                sb.AppendLine($"- **{_l.NavigationGroup}:** {entity.NavigationGroup}");
            if (!string.IsNullOrEmpty(entity.DefaultProperty))
                sb.AppendLine($"- **{_l.DisplayProperty}:** {entity.DefaultProperty}");
            sb.AppendLine($"- **{_l.Persistent}:** {(entity.IsPersistent ? _l.Yes : _l.No)}");
            if (entity.IsCloneable)
                sb.AppendLine($"- **{_l.Cloneable}:** {_l.Yes}");
            sb.AppendLine();

            if (entity.Properties.Count > 0)
            {
                sb.AppendLine($"### {_l.Properties}");
                sb.AppendLine();
                sb.AppendLine($"| {_l.Property} | {_l.Type} | {_l.Description} | {_l.Required} | {_l.Notes} |");
                sb.AppendLine("|-----------|------|-------------|-----------|-------|");

                foreach (var prop in entity.Properties.Where(p => !p.IsCollection))
                {
                    var notes = new List<string>();
                    if (prop.Size.HasValue) notes.Add($"Size:{prop.Size}");
                    if (prop.IsComputed) notes.Add(_l.Computed);
                    if (prop.ImmediatePostData) notes.Add("PostData");
                    if (!string.IsNullOrEmpty(prop.DisplayFormat)) notes.Add($"{_l.Format}:{prop.DisplayFormat}");
                    if (!string.IsNullOrEmpty(prop.DefaultValue)) notes.Add($"{_l.Default}:{prop.DefaultValue}");
                    if (!string.IsNullOrEmpty(prop.DataSourceCriteria)) notes.Add($"{_l.Filter}:{prop.DataSourceCriteria}");

                    sb.AppendLine($"| `{prop.Name}` | `{prop.TypeName}` | {prop.Description ?? ""} | {(prop.IsRequired ? _l.Yes : "")} | {string.Join(", ", notes)} |");
                }
                sb.AppendLine();
            }

            if (entity.Relationships.Count > 0)
            {
                sb.AppendLine($"### {_l.Relationships}");
                sb.AppendLine();
                foreach (var rel in entity.Relationships)
                {
                    var relType = rel.Type == RelationshipType.OneToMany ? _l.OneToMany : _l.ManyToOne;
                    var aggLabel = rel.IsAggregated ? $" ({_l.CompositionAggregation})" : "";
                    sb.AppendLine($"- **{rel.PropertyName}** -> `{rel.RelatedEntity}` ({relType}){aggLabel}");
                }
                sb.AppendLine();
            }

            if (entity.ValidationRules.Count > 0)
            {
                sb.AppendLine($"### {_l.ValidationRules}");
                sb.AppendLine();
                foreach (var rule in entity.ValidationRules)
                {
                    var target = !string.IsNullOrEmpty(rule.TargetProperty) ? $" in `{rule.TargetProperty}`" : "";
                    sb.AppendLine($"- **{rule.RuleType}**{target}: {rule.MessageTemplate ?? string.Join(", ", rule.Parameters.Select(p => $"{p.Key}={p.Value}"))}");
                }
                sb.AppendLine();
            }

            if (entity.AppearanceRules.Count > 0)
            {
                sb.AppendLine($"### {_l.AppearanceRules}");
                sb.AppendLine();
                foreach (var rule in entity.AppearanceRules)
                {
                    sb.AppendLine($"- **{rule.Id}**: {(rule.Visibility != null ? $"{_l.Visibility}={rule.Visibility}" : "")} {(rule.Enabled != null ? $"{_l.Enabled}={rule.Enabled}" : "")} {_l.When} `{rule.Criteria}`{(!string.IsNullOrEmpty(rule.TargetItems) ? $" ({rule.TargetItems})" : "")}");
                }
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine();
        }

        return new DocumentSection
        {
            Title = _l.BusinessEntities,
            FileName = $"{project.ProjectName}_Entities",
            Content = sb.ToString(),
            Description = string.Format(_l.EntitiesDescription, project.ProjectName),
            Tags = "entities,properties,relationships,validation,business-objects"
        };
    }

    /// <summary>
    /// Generates the controllers and actions section.
    /// </summary>
    private DocumentSection GenerateControllersSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.ControllersAndActions}");
        sb.AppendLine();

        foreach (var controller in project.Controllers)
        {
            sb.AppendLine($"## {controller.ClassName}");
            sb.AppendLine();
            sb.AppendLine($"- **{_l.BaseType}:** {controller.BaseControllerType}");
            if (!string.IsNullOrEmpty(controller.TargetObjectType))
                sb.AppendLine($"- **{_l.TargetEntity}:** {controller.TargetObjectType}");
            if (!string.IsNullOrEmpty(controller.TargetViewType))
                sb.AppendLine($"- **{_l.ViewType}:** {controller.TargetViewType}");
            if (controller.ReferencedEntities.Count > 0)
                sb.AppendLine($"- **{_l.ReferencedEntities}:** {string.Join(", ", controller.ReferencedEntities)}");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(controller.BusinessLogicSummary))
            {
                sb.AppendLine($"### {_l.BusinessLogicSummary}");
                sb.AppendLine();
                sb.AppendLine(controller.BusinessLogicSummary);
                sb.AppendLine();
            }

            if (controller.Actions.Count > 0)
            {
                sb.AppendLine($"### {_l.Actions}");
                sb.AppendLine();
                foreach (var action in controller.Actions)
                {
                    sb.AppendLine($"#### {action.Caption ?? action.ActionId}");
                    sb.AppendLine();
                    sb.AppendLine($"- **ID:** `{action.ActionId}`");
                    sb.AppendLine($"- **{_l.Type}:** {action.ActionType}");
                    if (!string.IsNullOrEmpty(action.Category))
                        sb.AppendLine($"- **{_l.Category}:** {action.Category}");
                    if (!string.IsNullOrEmpty(action.ImageName))
                        sb.AppendLine($"- **{_l.Icon}:** {action.ImageName}");
                    if (!string.IsNullOrEmpty(action.ConfirmationMessage))
                        sb.AppendLine($"- **{_l.Confirmation}:** \"{action.ConfirmationMessage}\"");
                    if (!string.IsNullOrEmpty(action.ToolTip))
                        sb.AppendLine($"- **{_l.Tooltip}:** {action.ToolTip}");
                    sb.AppendLine();

                    if (!string.IsNullOrEmpty(action.BusinessLogicSummary))
                    {
                        sb.AppendLine($"**{_l.ActionBusinessLogic}:**");
                        sb.AppendLine();
                        sb.AppendLine(action.BusinessLogicSummary);
                        sb.AppendLine();
                    }

                    if (!string.IsNullOrEmpty(action.ExecuteMethodBody))
                    {
                        sb.AppendLine($"**{_l.ExecutionLogic}:**");
                        sb.AppendLine();
                        sb.AppendLine("```csharp");
                        var lines = action.ExecuteMethodBody.Split('\n');
                        var truncated = lines.Length > 100;
                        foreach (var line in lines.Take(100))
                            sb.AppendLine(line);
                        if (truncated)
                            sb.AppendLine($"// ... ({lines.Length - 100} {_l.MoreLines})");
                        sb.AppendLine("```");
                        sb.AppendLine();
                    }
                }
            }

            if (controller.Methods.Count > 0)
            {
                sb.AppendLine($"### {_l.MainMethods}");
                sb.AppendLine();
                foreach (var method in controller.Methods.Where(m => m.IsPublic || m.Name.Contains("Calcular") || m.Name.Contains("Procesar") || m.Name.Contains("Obtener")))
                {
                    var paramList = string.Join(", ", method.Parameters);
                    sb.AppendLine($"- **{method.Name}({paramList})** -> `{method.ReturnType}`");
                }
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine();
        }

        return new DocumentSection
        {
            Title = _l.ControllersAndActions,
            FileName = $"{project.ProjectName}_Controllers",
            Content = sb.ToString(),
            Description = string.Format(_l.ControllersDescription, project.ProjectName),
            Tags = "controllers,actions,business-logic,workflows"
        };
    }

    /// <summary>
    /// Generates the business rules section.
    /// </summary>
    private DocumentSection GenerateBusinessRulesSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.BusinessRules}");
        sb.AppendLine();

        sb.AppendLine($"## {_l.ValidationRules}");
        sb.AppendLine();
        foreach (var entity in project.Entities.Where(e => e.ValidationRules.Count > 0))
        {
            sb.AppendLine($"### {entity.ClassName}");
            foreach (var rule in entity.ValidationRules)
            {
                sb.AppendLine($"- {rule.RuleType}: {rule.TargetProperty ?? _l.ClassLevel} - {string.Join(", ", rule.Parameters.Select(p => $"{p.Key}={p.Value}"))}");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"## {_l.ConditionalBehaviorRules}");
        sb.AppendLine();
        foreach (var entity in project.Entities.Where(e => e.AppearanceRules.Count > 0))
        {
            sb.AppendLine($"### {entity.ClassName}");
            foreach (var rule in entity.AppearanceRules)
            {
                sb.AppendLine($"- {_l.When} `{rule.Criteria}`: {(rule.Visibility != null ? $"{_l.Visibility}={rule.Visibility}" : "")} {(rule.Enabled != null ? $"{_l.Enabled}={rule.Enabled}" : "")} {(!string.IsNullOrEmpty(rule.TargetItems) ? $"({_l.Fields}: {rule.TargetItems})" : "")}");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"## {_l.ComputedPropertiesDerived}");
        sb.AppendLine();
        foreach (var entity in project.Entities)
        {
            var computed = entity.Properties.Where(p => p.IsComputed).ToList();
            if (computed.Count == 0) continue;

            sb.AppendLine($"### {entity.ClassName}");
            foreach (var prop in computed)
            {
                var alias = !string.IsNullOrEmpty(prop.PersistentAlias) ? $" = `{prop.PersistentAlias}`" : "";
                sb.AppendLine($"- **{prop.Name}** (`{prop.TypeName}`){alias}");
            }
            sb.AppendLine();
        }

        var allRules = project.Entities.SelectMany(e => e.InferredBusinessRules).ToList();
        if (allRules.Count > 0)
        {
            sb.AppendLine($"## {_l.ExplicitBusinessRules}");
            sb.AppendLine();
            foreach (var group in allRules.GroupBy(r => r.Category))
            {
                sb.AppendLine($"### {group.Key}");
                foreach (var rule in group)
                {
                    sb.AppendLine($"- {rule.Description}");
                }
                sb.AppendLine();
            }
        }

        return new DocumentSection
        {
            Title = _l.BusinessRules,
            FileName = $"{project.ProjectName}_BusinessRules",
            Content = sb.ToString(),
            Description = string.Format(_l.BusinessRulesDescription, project.ProjectName),
            Tags = "business-rules,validation,computed,conditional,logic"
        };
    }

    /// <summary>
    /// Generates module configuration and seed-data section.
    /// </summary>
    private DocumentSection GenerateConfigurationSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.ConfigurationAndSeedData}");
        sb.AppendLine();

        if (project.ModuleInfo != null)
        {
            sb.AppendLine($"## {_l.MainModule}");
            sb.AppendLine();
            sb.AppendLine($"- **{_l.Class}:** {project.ModuleInfo.ModuleClassName}");
            sb.AppendLine();

            if (project.ModuleInfo.RequiredModules.Count > 0)
            {
                sb.AppendLine($"### {_l.RequiredModules}");
                foreach (var mod in project.ModuleInfo.RequiredModules)
                    sb.AppendLine($"- {mod}");
                sb.AppendLine();
            }

            if (project.ModuleInfo.RegisteredTypes.Count > 0)
            {
                sb.AppendLine($"### {_l.RegisteredTypes}");
                foreach (var type in project.ModuleInfo.RegisteredTypes)
                    sb.AppendLine($"- {type}");
                sb.AppendLine();
            }
        }

        if (project.SeedData.Count > 0)
        {
            sb.AppendLine($"## {_l.SeedData}");
            sb.AppendLine();
            sb.AppendLine(_l.SeedDataDescription);
            sb.AppendLine();

            foreach (var seed in project.SeedData)
            {
                sb.AppendLine($"### {seed.Description}");
                sb.AppendLine();
                sb.AppendLine($"**{_l.Entity}:** `{seed.EntityType}` | **{_l.Method}:** `{seed.MethodName}`");
                sb.AppendLine();

                if (seed.Records.Count > 0)
                {
                    var allKeys = seed.Records.SelectMany(r => r.PropertyValues.Keys).Distinct().ToList();
                    if (allKeys.Count > 0)
                    {
                        sb.AppendLine("| " + string.Join(" | ", allKeys) + " |");
                        sb.AppendLine("| " + string.Join(" | ", allKeys.Select(_ => "---")) + " |");
                        foreach (var record in seed.Records)
                        {
                            var values = allKeys.Select(k => record.PropertyValues.GetValueOrDefault(k, ""));
                            sb.AppendLine("| " + string.Join(" | ", values) + " |");
                        }
                        sb.AppendLine();
                    }
                }

                if (!string.IsNullOrEmpty(seed.RawSourceCode))
                {
                    sb.AppendLine("<details>");
                    sb.AppendLine($"<summary>{_l.SourceCodeOf} {seed.MethodName}</summary>");
                    sb.AppendLine();
                    sb.AppendLine("```csharp");
                    sb.AppendLine(seed.RawSourceCode);
                    sb.AppendLine("```");
                    sb.AppendLine("</details>");
                    sb.AppendLine();
                }
            }
        }

        return new DocumentSection
        {
            Title = _l.ConfigurationAndSeedData,
            FileName = $"{project.ProjectName}_Configuration",
            Content = sb.ToString(),
            Description = string.Format(_l.ConfigurationDescription, project.ProjectName),
            Tags = "configuration,seed-data,module,initialization,setup"
        };
    }

    /// <summary>
    /// Generates application navigation section.
    /// </summary>
    private DocumentSection GenerateNavigationSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.NavigationStructure}");
        sb.AppendLine();
        sb.AppendLine($"## {_l.ApplicationMenu}");
        sb.AppendLine();

        foreach (var nav in project.Navigation)
        {
            sb.AppendLine($"### {nav.GroupName}");
            sb.AppendLine();
            foreach (var entityName in nav.EntityClassNames)
            {
                var entity = project.Entities.FirstOrDefault(e => e.ClassName == entityName);
                if (entity == null) continue;

                sb.AppendLine($"#### {entityName}");
                if (!string.IsNullOrEmpty(entity.Description))
                    sb.AppendLine($"*{entity.Description}*");
                sb.AppendLine();
                sb.AppendLine($"- **{_l.MainProperties}:** {string.Join(", ", entity.Properties.Where(p => !p.IsCollection && p.VisibleInListView).Take(8).Select(p => p.Name))}");
                if (entity.Relationships.Count > 0)
                    sb.AppendLine($"- **{_l.Relationships}:** {string.Join(", ", entity.Relationships.Select(r => $"{r.PropertyName}→{r.RelatedEntity}"))}");
                sb.AppendLine();
            }
        }

        var orphans = project.Entities.Where(e => string.IsNullOrEmpty(e.NavigationGroup)).ToList();
        if (orphans.Count > 0)
        {
            sb.AppendLine($"### {_l.WithoutNavigationGroup}");
            sb.AppendLine();
            foreach (var entity in orphans)
            {
                sb.AppendLine($"- **{entity.ClassName}** ({entity.BaseType})");
            }
        }

        return new DocumentSection
        {
            Title = _l.NavigationStructure,
            FileName = $"{project.ProjectName}_Navigation",
            Content = sb.ToString(),
            Description = string.Format(_l.NavigationDescription, project.ProjectName),
            Tags = "navigation,menu,structure,ui"
        };
    }

    /// <summary>
    /// Generates Model Editor customization section from xafml metadata.
    /// </summary>
    private DocumentSection GenerateModelEditorSection(ExtractedProject project)
    {
        var model = project.ModelEditorInfo!;
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.ModelEditorCustomizations}");
        sb.AppendLine();

        if (model.Options != null)
        {
            sb.AppendLine($"## {_l.ApplicationOptions}");
            sb.AppendLine();
            if (model.Options.UIType != null) sb.AppendLine($"- **{_l.UITypeLabel}:** {model.Options.UIType}");
            if (model.Options.FormStyle != null) sb.AppendLine($"- **{_l.FormStyleLabel}:** {model.Options.FormStyle}");
            if (model.Options.Skin != null) sb.AppendLine($"- **{_l.VisualTheme}:** {model.Options.Skin}");
            if (model.Options.RequiredFieldMark != null) sb.AppendLine($"- **{_l.RequiredFieldMark}:** {model.Options.RequiredFieldMark}");
            sb.AppendLine();
        }

        if (model.BOModelClasses.Count > 0)
        {
            sb.AppendLine($"## {_l.BOModelCustomizations}");
            sb.AppendLine();
            sb.AppendLine($"| {_l.Class} | {_l.Caption} | {_l.Cloneable} | {_l.Other} |");
            sb.AppendLine("|-------|---------|----------|-------|");
            foreach (var cls in model.BOModelClasses)
            {
                var others = cls.CustomAttributes.Count > 0
                    ? string.Join(", ", cls.CustomAttributes.Select(kv => $"{kv.Key}={kv.Value}"))
                    : "";
                sb.AppendLine($"| `{cls.ClassName}` | {cls.Caption ?? ""} | {(cls.IsCloneable ? _l.Yes : "")} | {others} |");
            }
            sb.AppendLine();
        }

        if (model.Views.Count > 0)
        {
            sb.AppendLine($"## {_l.ViewCustomizations}");
            sb.AppendLine();
            foreach (var view in model.Views)
            {
                sb.AppendLine($"### {view.Id} ({view.ViewType})");
                sb.AppendLine();
                if (view.Caption != null) sb.AppendLine($"- **{_l.Caption}:** {view.Caption}");
                if (view.AllowEdit.HasValue) sb.AppendLine($"- **{_l.Editable}:** {(view.AllowEdit.Value ? _l.Yes : _l.No)}");
                if (view.AllowDelete.HasValue) sb.AppendLine($"- **{_l.AllowDelete}:** {(view.AllowDelete.Value ? _l.Yes : _l.No)}");
                if (view.AllowNew.HasValue) sb.AppendLine($"- **{_l.AllowCreate}:** {(view.AllowNew.Value ? _l.Yes : _l.No)}");
                if (view.Criteria != null) sb.AppendLine($"- **{_l.FilterCriteria}:** `{view.Criteria}`");
                if (view.EditorTypeName != null) sb.AppendLine($"- **{_l.CustomEditor}:** `{view.EditorTypeName}`");

                if (view.Columns.Count > 0)
                {
                    sb.AppendLine();
                    sb.AppendLine($"**{_l.ConfiguredColumns}:**");
                    sb.AppendLine();
                    sb.AppendLine($"| {_l.Property} | {_l.Order} | {_l.Width} | {_l.Sorting} | {_l.Caption} |");
                    sb.AppendLine("|-----------|-------|-------|-------------|---------|");
                    foreach (var col in view.Columns.OrderBy(c => c.Index ?? 999))
                    {
                        sb.AppendLine($"| `{col.PropertyName ?? col.Id}` | {col.Index?.ToString() ?? ""} | {col.Width?.ToString() ?? ""} | {col.SortOrder ?? ""} | {col.Caption ?? ""} |");
                    }
                    sb.AppendLine();
                }

                if (view.Filters.Count > 0)
                {
                    sb.AppendLine($"**{_l.PredefinedFilters}:**");
                    sb.AppendLine();
                    foreach (var filter in view.Filters)
                    {
                        sb.AppendLine($"- **{filter.Caption ?? filter.Id}**: `{filter.Criteria}`");
                    }
                    sb.AppendLine();
                }
            }
        }

        if (model.NavigationItems != null && model.NavigationItems.Groups.Count > 0)
        {
            sb.AppendLine($"## {_l.NavigationModelEditor}");
            sb.AppendLine();
            if (model.NavigationItems.NavigationStyle != null)
                sb.AppendLine($"- **{_l.Style}:** {model.NavigationItems.NavigationStyle}");
            if (model.NavigationItems.StartupNavigationItem != null)
                sb.AppendLine($"- **{_l.StartupView}:** {model.NavigationItems.StartupNavigationItem}");
            sb.AppendLine();

            foreach (var group in model.NavigationItems.Groups)
            {
                sb.AppendLine($"### {group.Caption ?? group.Id}");
                foreach (var item in group.Items.OrderBy(i => i.Index ?? 999))
                {
                    var icon = item.ImageName != null ? $" ({_l.Icon}: {item.ImageName})" : "";
                    var viewRef = item.ViewId != null ? $" -> `{item.ViewId}`" : "";
                    sb.AppendLine($"- **{item.Caption ?? item.Id}**{viewRef}{icon}");
                }
                sb.AppendLine();
            }
        }

        if (model.SchemaModules.Count > 0)
        {
            sb.AppendLine($"## {_l.RegisteredSchemaModules}");
            sb.AppendLine();
            foreach (var mod in model.SchemaModules)
            {
                sb.AppendLine($"- **{mod.Name}** v{mod.Version}");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"## {_l.ProcessedXafmlFiles}");
        sb.AppendLine();
        foreach (var f in model.SourceFiles)
        {
            sb.AppendLine($"- `{Path.GetFileName(f)}` ({Path.GetDirectoryName(f)})");
        }

        return new DocumentSection
        {
            Title = _l.ModelEditorCustomizations,
            FileName = $"{project.ProjectName}_ModelEditor",
            Content = sb.ToString(),
            Description = string.Format(_l.ModelEditorDescription, project.ProjectName),
            Tags = "model-editor,xafml,views,columns,filters,ui-customization"
        };
    }
}
