using System.Text;
using System.Text.Json;
using XafLogicExplainer.Core.Interfaces;
using XafLogicExplainer.Core.Models;

namespace XafLogicExplainer.Core.Generators;

/// <summary>
/// Generates markdown and JSON documentation artifacts from extracted project metadata.
/// </summary>
public class MarkdownDocumentationGenerator : IDocumentationGenerator
{
    private readonly DocumentationLabels _l;
    private readonly bool _spanish;

    /// <summary>
    /// Creates a documentation generator for the selected language.
    /// </summary>
    /// <param name="languageCode">Language code used for labels and section captions.</param>
    public MarkdownDocumentationGenerator(string languageCode = "es")
    {
        _l = DocumentationLabels.ForLanguage(languageCode);
        _spanish = languageCode.StartsWith("es", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Picks the wording for the current language.
    /// </summary>
    /// <remarks>
    /// For prose that belongs to one section, where a label on <see cref="DocumentationLabels"/>
    /// would be a caption used once.
    /// </remarks>
    /// <param name="es">Spanish text.</param>
    /// <param name="en">English text.</param>
    private string L(string es, string en) => _spanish ? es : en;

    /// <summary>
    /// Generates a full combined markdown document.
    /// </summary>
    /// <param name="project">Extracted project snapshot.</param>
    /// <returns>Full markdown document.</returns>
    public string GenerateMarkdown(ExtractedProject project)
    {
        var sections = GenerateSections(project);
        var sb = new StringBuilder();

        sb.AppendLine($"# {project.ProjectName} - {_l.FunctionalDocumentation}");
        sb.AppendLine();
        sb.AppendLine($"*Generated: {project.ExtractedAt}*");
        // Only when one was read. `*Framework: *` is a field with nothing in it, which reads as
        // a broken document rather than as the honest "this was not declared".
        if (!string.IsNullOrWhiteSpace(project.TargetFramework))
            sb.AppendLine($"*Framework: {project.TargetFramework}*");
        sb.AppendLine();

        foreach (var section in sections)
        {
            sb.AppendLine(section.Content);
            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>
    /// Serializes project extraction output as JSON.
    /// </summary>
    /// <param name="project">Extracted project snapshot.</param>
    /// <returns>JSON representation of the project.</returns>
    public string GenerateJson(ExtractedProject project)
    {
        return JsonSerializer.Serialize(project, JsonOptions);
    }

    /// <summary>
    /// Deserializes an extracted project from JSON.
    /// </summary>
    /// <param name="json">JSON payload generated by this toolchain.</param>
    /// <returns>Deserialized project model or null when payload is invalid.</returns>
    public static ExtractedProject? DeserializeProject(string json)
    {
        return JsonSerializer.Deserialize<ExtractedProject>(json, JsonOptions);
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    /// <summary>
    /// Generates all standalone documentation sections for upload or local export.
    /// </summary>
    /// <param name="project">Extracted project snapshot.</param>
    /// <returns>List of generated sections.</returns>
    public List<DocumentSection> GenerateSections(ExtractedProject project)
    {
        var sections = new List<DocumentSection>
        {
            GenerateOverviewSection(project),
            GenerateEntitiesSection(project),
            GenerateControllersSection(project),
            GenerateBusinessRulesSection(project),
            GenerateConfigurationSection(project),
            GenerateNavigationSection(project),
        };

        if (project.ModelEditorInfo != null)
            sections.Add(GenerateModelEditorSection(project));

        if (project.Views.Count > 0)
            sections.Add(GenerateScreensSection(project));

        // Only when the application has something to say about reports. One that never registered
        // ReportsModuleV2 and ships no layouts gets no section rather than an empty one — "no
        // reports" is worth printing when it is a finding, not when it is the default.
        if (project.ReferencesReportsModule
            || project.Reports.Count > 0
            || project.UnregisteredReportLayouts.Count > 0)
        {
            sections.Add(GenerateReportsSection(project));
        }

        return sections;
    }

    /// <summary>
    /// The reports an application declares, and what the repository cannot show.
    /// </summary>
    /// <remarks>
    /// The sentence under the heading does more work than the list. Reports V2 lets users build
    /// reports at run time in the End-User Designer, and those are stored as rows rather than
    /// files, so an extraction that reads source can never see them. An application with forty
    /// user-designed reports and none in its repository is the ordinary case rather than an exotic
    /// one — checked against a production application where <c>ReportsModuleV2</c> is registered,
    /// the store mode is the database, and the source contains no report at all.
    /// <para>
    /// Printing "no reports" there would not be an incomplete answer but a wrong one, and the more
    /// use an application makes of reports the wronger it would get.
    /// </para>
    /// </remarks>
    private DocumentSection GenerateReportsSection(ExtractedProject project)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"## {L("Reportes", "Reports")}");
        sb.AppendLine();
        sb.AppendLine(ReportsPreamble(project));
        sb.AppendLine();

        // One layout can carry several registrations — the same `.repx` offered both from the
        // navigation and in place on a list view is an ordinary pair. Rendering the filter, the
        // bindings and the whole of `GetCriteria()` again under the second one buries the
        // difference between them, which is the only thing a reader opened it for.
        var alreadyShown = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var report in project.Reports)
            AppendReport(sb, project, report, alreadyShown);

        AppendUnregisteredReports(sb, project);

        return new DocumentSection
        {
            Title = L("Reportes", "Reports"),
            Content = sb.ToString().TrimEnd(),
        };
    }

    /// <summary>
    /// What the list of reports is: all of them, a lower bound, or an absence worth explaining.
    /// </summary>
    private string ReportsPreamble(ExtractedProject project)
    {
        if (!project.ReferencesReportsModule)
        {
            return L(
                $"Se leyeron {project.Reports.Count} reportes del codigo. Esta aplicacion no registra "
                + "`ReportsModuleV2`, asi que estos son todos los que hay.",
                $"{project.Reports.Count} reports read from source. This application does not register "
                + "`ReportsModuleV2`, so these are all of them.");
        }

        if (project.Reports.Count == 0)
        {
            return L(
                "Esta aplicacion registra `ReportsModuleV2` y **no declara ningun reporte en el "
                + "codigo**. Eso casi nunca significa que no tenga reportes: con ese modulo, los "
                + "usuarios los disenan en tiempo de ejecucion y quedan guardados como filas en la "
                + "base de datos. Leer el repositorio no puede mostrarlos, y el numero real no es "
                + "cero sino desconocido.",
                "This application registers `ReportsModuleV2` and **declares no reports in source**. "
                + "That rarely means it has none: with that module in, users design reports at run "
                + "time and they are stored as rows in the database. Reading the repository cannot "
                + "show them, and the true number is not zero but unknown.");
        }

        return L(
            $"Se leyeron {project.Reports.Count} reportes del codigo. Esta aplicacion tambien registra "
            + "`ReportsModuleV2`, con lo que los usuarios pueden crear los suyos en tiempo de "
            + "ejecucion; esos viven en la base de datos, asi que **esta lista es una cota inferior**.",
            $"{project.Reports.Count} reports read from source. This application also registers "
            + "`ReportsModuleV2`, so users can build their own at run time; those live in the "
            + "database, which makes **this list a lower bound**.");
    }

    private void AppendReport(
        StringBuilder sb, ExtractedProject project, ExtractedReport report,
        Dictionary<string, string> alreadyShown)
    {
        sb.AppendLine($"### {report.DisplayName}");
        sb.AppendLine();
        sb.AppendLine($"- **{L("Sobre", "Over")}:** `{report.DataType}`");
        sb.AppendLine($"- **{L("Clase del reporte", "Report class")}:** `{report.ReportType}`");

        if (report.ParametersType is { Length: > 0 } parameters)
            sb.AppendLine($"- **{L("Dialogo previo", "Opens with")}:** `{parameters}`");

        // Null is not false. The registration overload that says nothing about in-place reporting
        // leaves XAF's own default in charge, and reporting "no" there would be an invention.
        if (report.IsInplaceReport is { } inplace)
        {
            sb.AppendLine($"- **{L("En la lista del objeto", "Offered in place")}:** "
                + (inplace ? L("si", "yes") : L("no", "no")));
        }

        var registeredAt = SourceCitation.Of(project, report.FilePath, report.Line);

        if (registeredAt.Length > 0)
            sb.AppendLine($"- **{L("Registrado en", "Registered at")}:** {registeredAt}");

        sb.AppendLine();

        // Keyed by what is actually shared. Two registrations of one `.repx` differ in their
        // options, which are printed above, and in nothing below.
        var key = $"{report.Layout?.FilePath}|{report.Layout?.Line}|{report.ParametersObject?.ClassName}";

        if (report.Layout is not null || report.ParametersObject is not null)
        {
            if (alreadyShown.TryGetValue(key, out var shownUnder))
            {
                sb.AppendLine(L(
                    $"Mismo diseno y dialogo que **{shownUnder}**, arriba.",
                    $"Same layout and dialog as **{shownUnder}**, above."));
                sb.AppendLine();

                return;
            }

            alreadyShown[key] = report.DisplayName;
        }

        AppendLayout(sb, project, report.Layout);
        AppendParametersObject(sb, project, report.ParametersObject);
    }

    /// <summary>
    /// What a report shows: the decisions in its layout, not its appearance.
    /// </summary>
    private void AppendLayout(StringBuilder sb, ExtractedProject project, ReportLayout? layout)
    {
        if (layout is null)
            return;

        var at = SourceCitation.Of(project, layout.FilePath, layout.Line);

        sb.AppendLine($"{L("Diseno leido de", "Layout read from")} {LayoutSource(layout.Source)}"
            + (at.Length > 0 ? $", {at}" : "") + ".");
        sb.AppendLine();

        if (layout.DataSource is { Length: > 0 } source)
        {
            var member = layout.DataMember is { Length: > 0 } dataMember ? $" / `{dataMember}`" : "";
            sb.AppendLine($"- **{L("Origen de datos", "Data source")}:** `{source}`{member}");
        }

        // The filter is the most consequential line in a report and the one nothing else in the
        // repository mentions: "approved only", "this fiscal year", "excluding cancelled".
        if (layout.FilterString is { Length: > 0 } filter)
            sb.AppendLine($"- **{L("Filtra por", "Filters on")}:** `{filter}`");

        if (layout.GroupFields.Count > 0)
        {
            sb.AppendLine($"- **{L("Agrupa por", "Grouped by")}:** "
                + string.Join(", ", layout.GroupFields.Select(field => $"`{field}`")));
        }

        if (layout.CalculatedFields.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine($"**{L("Campos calculados", "Calculated fields")}**");
            sb.AppendLine();
            sb.AppendLine($"| {L("Nombre", "Name")} | {L("Expresion", "Expression")} |");
            sb.AppendLine("| --- | --- |");

            foreach (var field in layout.CalculatedFields)
                sb.AppendLine($"| `{field.Name}` | `{field.Expression}` |");
        }

        if (layout.Bindings.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine($"**{L("Expresiones en el diseno", "Expressions in the layout")}**");
            sb.AppendLine();
            sb.AppendLine($"| {L("Control", "Control")} | {L("Propiedad", "Property")} | "
                + $"{L("Expresion", "Expression")} |");
            sb.AppendLine("| --- | --- | --- |");

            foreach (var binding in layout.Bindings)
                sb.AppendLine($"| `{binding.Control}` | `{binding.Property}` | `{binding.Expression}` |");
        }

        sb.AppendLine();
    }

    private void AppendParametersObject(
        StringBuilder sb, ExtractedProject project, ReportParametersObject? parameters)
    {
        if (parameters is null)
            return;

        var at = SourceCitation.Of(project, parameters.FilePath, parameters.Line);

        sb.AppendLine($"**{L("El dialogo pide", "The dialog asks for")}** — `{parameters.ClassName}`"
            + (at.Length > 0 ? $", {at}" : "") + ".");
        sb.AppendLine();

        if (parameters.Fields.Count > 0)
        {
            sb.AppendLine($"| {L("Campo", "Field")} | {L("Tipo", "Type")} | "
                + $"{L("Por defecto", "Default")} |");
            sb.AppendLine("| --- | --- | --- |");

            foreach (var field in parameters.Fields)
            {
                var fallback = field.Default is { Length: > 0 } value ? $"`{value}`" : "";
                sb.AppendLine($"| `{field.Name}` | `{field.Type}` | {fallback} |");
            }

            sb.AppendLine();
        }

        // What the answers are turned into. This is the business logic of the dialog, and the
        // reason the parameters object is worth reading rather than merely naming.
        if (parameters.CriteriaSource is { Length: > 0 } criteria)
        {
            sb.AppendLine(L("Con esas respuestas filtra", "Those answers become the filter") + ":");
            sb.AppendLine();
            sb.AppendLine("```csharp");
            sb.AppendLine(criteria.Trim());
            sb.AppendLine("```");
            sb.AppendLine();
        }

        if (parameters.SortingSource is { Length: > 0 } sorting)
        {
            sb.AppendLine(L("Y el orden", "And the sort order") + ":");
            sb.AppendLine();
            sb.AppendLine("```csharp");
            sb.AppendLine(sorting.Trim());
            sb.AppendLine("```");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Layouts and dialogs that exist in the repository and that nothing registers.
    /// </summary>
    /// <remarks>
    /// A shop that designs reports outside Visual Studio keeps the exports beside the module and
    /// imports them into the database by hand, so these files are real work that no registration
    /// claims. Listing them as unregistered is the difference between "this exists and nothing in
    /// the code points at it" and silence.
    /// </remarks>
    private void AppendUnregisteredReports(StringBuilder sb, ExtractedProject project)
    {
        if (project.UnregisteredReportLayouts.Count == 0
            && project.UnregisteredReportParameters.Count == 0)
        {
            return;
        }

        sb.AppendLine($"### {L("Disenos que nadie registra", "Layouts nothing registers")}");
        sb.AppendLine();
        sb.AppendLine(L(
            "Estos archivos estan en el repositorio y ninguna llamada de registro los nombra. "
            + "Normalmente son disenos exportados de la aplicacion e importados a mano a la base "
            + "de datos, asi que son trabajo real que el codigo no menciona.",
            "These files are in the repository and no registration call names them. Usually they "
            + "are layouts exported from the running application and imported into the database by "
            + "hand — real work that the code never mentions."));
        sb.AppendLine();

        foreach (var layout in project.UnregisteredReportLayouts)
        {
            var at = SourceCitation.Of(project, layout.FilePath, layout.Line);
            var filter = layout.FilterString is { Length: > 0 } criteria
                ? $" — {L("filtra por", "filters on")} `{criteria}`"
                : "";

            sb.AppendLine($"- {at}{filter}");
        }

        foreach (var parameters in project.UnregisteredReportParameters)
        {
            var at = SourceCitation.Of(project, parameters.FilePath, parameters.Line);

            sb.AppendLine($"- `{parameters.ClassName}` — "
                + L("dialogo de parametros que ningun reporte nombra",
                    "a parameters dialog no report names")
                + (at.Length > 0 ? $", {at}" : ""));
        }

        sb.AppendLine();
    }

    private string LayoutSource(ReportLayoutSource source) => source switch
    {
        ReportLayoutSource.DesignerCode => L("el codigo del disenador", "designer code"),
        ReportLayoutSource.Repx => L("un archivo `.repx`", "a `.repx` file"),
        _ => L("el codigo del reporte", "the report's own code"),
    };

    /// <summary>Says which class a folded declaration came from, for a line that has room.</summary>
    private string Declarer(string? inheritedFrom)
        => inheritedFrom is { Length: > 0 } ? $" — {Inherited(inheritedFrom)}" : "";

    /// <summary>Says which class a folded declaration came from, for a cell that has none.</summary>
    private string Inherited(string declarer) => $"{L("heredado de", "inherited from")} `{declarer}`";

    /// <summary>
    /// Names a validation rule the way the rest of the application does, when it was named.
    /// </summary>
    /// <remarks>
    /// The identifier is what a validation error carries and what the Model Editor lists it under,
    /// so it is how a reader gets from this line back to the thing itself.
    /// <para>
    /// The contexts are shown only when they are not the ordinary save, because on the ordinary
    /// save they are true of nearly every rule and say nothing. When they are anything else they
    /// are the whole story: the rule does not run where a reader would assume it does.
    /// </para>
    /// </remarks>
    private string RuleName(ExtractedValidationRule rule)
    {
        var id = rule.Id is { Length: > 0 } ? $" `{rule.Id}`" : "";

        var unusualContext = rule.Contexts is { Length: > 0 } contexts
                             && contexts is not ("DefaultContexts.Save" or "Save");

        return unusualContext ? $"{id} ({L("contexto", "context")} `{rule.Contexts}`)" : id;
    }

    /// <summary>
    /// Says what a validation rule enforces and what the user is told when it fires.
    /// </summary>
    /// <remarks>
    /// This printed the attribute's raw arguments — <c>arg0=Sale_TotalNotNegative,
    /// arg1=DefaultContexts.Save</c> — because those were the only fields the reader of an
    /// attribute filled in. Anything still unrecognised is kept, by value: dropping it would trade
    /// one unreadable rendering for a silently incomplete one, and <c>RuleRange</c>'s bounds are
    /// exactly the kind of argument that lives there.
    /// </remarks>
    private string DescribeRule(ExtractedValidationRule rule)
    {
        var known = new[] { rule.Id, rule.Contexts, rule.Expression, rule.MessageTemplate, rule.TargetCriteria };
        var parts = new List<string>();

        if (rule.Expression is { Length: > 0 }) parts.Add($"`{rule.Expression}`");

        parts.AddRange(rule.Parameters
            .Where(p => !known.Contains(p.Value, StringComparer.Ordinal))
            .Select(p => p.Key.StartsWith("arg", StringComparison.Ordinal) ? p.Value : $"{p.Key}={p.Value}"));

        if (rule.MessageTemplate is { Length: > 0 }) parts.Add($"“{rule.MessageTemplate}”");
        if (rule.TargetCriteria is { Length: > 0 }) parts.Add($"{_l.When} `{rule.TargetCriteria}`");

        // Empty rather than "no arguments": a [RuleRequiredField] whose id and contexts are
        // already on the line has nothing further to say, and saying so reads as a gap.
        return parts.Count > 0 ? $": {string.Join(" — ", parts)}" : "";
    }

    /// <summary>
    /// Opens an appearance rule's line: what it is called, and what activates it.
    /// </summary>
    /// <remarks>
    /// Both halves are optional in real code, and both were printed as though they were not.
    /// <para>
    /// A rule written on a property needs no identifier — the property already says what it governs
    /// — and the DevExpress non-persistent-objects demo writes <c>[Appearance("", Enabled = false)]</c>
    /// at class level. The empty name rendered as <c>****</c>.
    /// </para>
    /// <para>
    /// A rule with no criteria is not a rule whose condition went missing: in XAF it is
    /// <em>always</em> active, which is the stronger of the two claims and the one a reader most
    /// needs. It rendered as <c>when ``</c> — a condition that looks like it failed to load.
    /// <see cref="HtmlExplainerGenerator"/> had already settled on the right word.
    /// </para>
    /// </remarks>
    private string OpenAppearance(ExtractedAppearanceRule rule)
    {
        var condition = rule.Criteria is { Length: > 0 } criteria ? $"{_l.When} `{criteria}`" : _l.Always;

        // No identifier leaves nothing to put in front of the condition, and an empty bold span is
        // worse than none: DescribeAppearance names the targets, which is what identifies it.
        return rule.Id is { Length: > 0 } id ? $"**{id}** — {condition}" : condition;
    }

    /// <summary>
    /// Says what an appearance rule actually does, and on which screen.
    /// </summary>
    /// <remarks>
    /// It used to print the visibility and the enabled flag only, so a rule whose whole effect is
    /// a red font read as "when OnHand = 0 ()" — a condition with no consequence, on no stated
    /// screen. The context matters as much: the same criteria colours a list and does nothing in a
    /// detail view.
    /// </remarks>
    private string DescribeAppearance(ExtractedAppearanceRule rule)
    {
        var effects = new List<string>();

        if (rule.Visibility is { Length: > 0 }) effects.Add($"{_l.Visibility}={rule.Visibility}");
        if (rule.Enabled is { Length: > 0 }) effects.Add($"{_l.Enabled}={rule.Enabled}");
        if (rule.FontColor is { Length: > 0 }) effects.Add($"{L("color de letra", "font colour")}={rule.FontColor}");
        if (rule.BackColor is { Length: > 0 }) effects.Add($"{L("color de fondo", "back colour")}={rule.BackColor}");

        var where = new List<string>();

        if (rule.Context is { Length: > 0 }) where.Add($"{L("en", "in")} {rule.Context}");
        if (rule.TargetItems is { Length: > 0 }) where.Add($"{TargetKind(rule)}: {rule.TargetItems}");

        var text = effects.Count > 0 ? $": {string.Join(", ", effects)}" : $": {L("sin efecto declarado", "no declared effect")}";

        return where.Count > 0 ? $"{text} ({string.Join(", ", where)})" : text;
    }

    /// <summary>
    /// What kind of thing the rule's targets are.
    /// </summary>
    /// <remarks>
    /// Every target used to be called a field, so a rule disabling the <c>Delete</c> action read as
    /// governing a column called Delete — a column no reader would find, described confidently. XAF
    /// defaults the type to <c>ViewItem</c>, so an absent one is a field and the common case is
    /// unchanged.
    /// </remarks>
    private string TargetKind(ExtractedAppearanceRule rule) => rule.AppearanceItemType switch
    {
        "Action" => L("acciones", "actions"),
        "LayoutItem" => L("elementos de layout", "layout items"),
        _ => _l.Fields,
    };

    /// <summary>Joins controller names for a one-line mention.</summary>
    private static string Names(IEnumerable<ViewActivation> activations) =>
        string.Join(", ", activations
            .OrderBy(a => a.Controller, StringComparer.Ordinal)
            .Select(a => $"`{a.Controller}`"));

    /// <summary>
    /// Says in one phrase what kind of view this is, where it appears, and where it came from.
    /// </summary>
    /// <remarks>
    /// Written out rather than printed as three enum names, which would leave English words inside
    /// the Spanish document. The view class names stay as they are: <c>DetailView</c> is what XAF
    /// calls it, in either language.
    /// </remarks>
    private string DescribeView(ExtractedView view)
    {
        var kind = view.ViewType switch
        {
            ModelViewType.ListView when view.Id.EndsWith("_LookupListView", StringComparison.Ordinal) =>
                L("Vista de busqueda", "Lookup list view"),
            ModelViewType.ListView => L("Vista de lista", "List view"),
            ModelViewType.DetailView => L("Vista de detalle", "Detail view"),
            _ => L("Dashboard", "Dashboard"),
        };

        var where = view.Nesting switch
        {
            ViewNesting.Root => L("raiz", "root"),
            ViewNesting.Nested => L("anidada", "nested"),
            _ => L("raiz o anidada", "root or nested"),
        };

        var origin = view.Origin switch
        {
            ViewOrigin.Generated => L("generada por XAF, no existe en ningun archivo",
                                      "generated by XAF, exists in no file"),
            ViewOrigin.Customized => L("generada por XAF y personalizada en el Model Editor",
                                       "generated by XAF and customized in the Model Editor"),
            _ => L("definida en el Model Editor", "defined in the Model Editor"),
        };

        return $"{kind}, {where}, {origin}";
    }

    /// <summary>
    /// Generates the screen inventory: every view, and what XAF loads onto it.
    /// </summary>
    /// <remarks>
    /// Kept out of the always-loaded index on purpose — an application of any size has hundreds of
    /// views, and this is the file to open when the question is about one screen.
    /// </remarks>
    private DocumentSection GenerateScreensSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.Screens}");
        sb.AppendLine();
        sb.AppendLine(L(
            $"{project.Views.Count} vistas. XAF genera una vista de lista, una de detalle y una de busqueda " +
            "por cada clase de negocio, mas una lista por cada coleccion, asi que la mayoria no existe en " +
            "ningun archivo: buscarlas en el codigo no encuentra nada, y eso no significa que falten.",
            $"{project.Views.Count} views. XAF generates a list, a detail and a lookup view for every " +
            "business class, plus a list view for every collection, so most of these exist in no file: " +
            "searching the source tree for one finds nothing, and that is not evidence it is missing."));

        foreach (var group in project.Views
                     .GroupBy(v => v.ObjectType ?? "-")
                     .OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            sb.AppendLine();
            sb.AppendLine($"## {group.Key}");
            sb.AppendLine();

            foreach (var view in group.OrderBy(v => v.Id, StringComparer.Ordinal))
            {
                sb.AppendLine($"### {view.Id}");
                sb.AppendLine();
                sb.AppendLine($"- {DescribeView(view)}");

                if (view.InNavigation)
                    sb.AppendLine(L("- Abierta desde la navegacion", "- Opened from navigation"));

                if (view.OwnerProperty is { } ownerProperty)
                    sb.AppendLine($"- {L("Mostrada por", "Shown by")} `{view.OwnerEntity}.{ownerProperty}`");

                var mine = view.Activates.Where(a => !a.Framework).ToList();
                var framework = view.Activates.Where(a => a.Framework).ToList();

                if (mine.Count == 0)
                {
                    sb.AppendLine(L(
                        "- Ningun controlador de esta aplicacion se activa aqui.",
                        "- No controller of this application activates here."));
                }

                foreach (var activation in mine)
                {
                    sb.Append($"- `{activation.Controller}` — ");
                    sb.AppendLine(activation.Reasons.Count == 0
                        ? L("no restringe nada, corre en todas las vistas",
                            "restricts nothing, runs on every view")
                        : string.Join(L(", y ", ", and "), activation.Reasons
                            .Select(reason => ActivationReasonText.ForLanguage(reason, _spanish))));

                    if (activation.Replaces.Count > 0)
                    {
                        sb.AppendLine($"  - {L("Reemplaza a", "Replaces")} " +
                                      string.Join(", ", activation.Replaces.Select(name => $"`{name}`")));
                    }

                    foreach (var action in activation.Actions)
                        sb.AppendLine($"  - {action}");
                }

                // Named but not expanded: inherited behaviour, and a lot of it. Giving each entry
                // the weight of the team's own would bury the line worth reading.
                if (framework.Count > 0)
                {
                    sb.AppendLine(L(
                        $"- Ademas, de XAF: {Names(framework)}",
                        $"- Plus, from XAF: {Names(framework)}"));
                }

                sb.AppendLine();
            }
        }

        if (project.FrameworkAlwaysActive.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine($"## {L("Controladores de XAF en todas las pantallas", "XAF controllers on every screen")}");
            sb.AppendLine();
            sb.AppendLine(L(
                $"Estos no restringen nada, asi que se cargan en las {project.Views.Count} pantallas de " +
                "arriba. Listados una vez y no en cada una.",
                $"These restrict nothing, so they load onto all {project.Views.Count} screens above. " +
                "Listed once rather than under each."));
            sb.AppendLine();
            sb.AppendLine(string.Join(", ", project.FrameworkAlwaysActive.Select(name => $"`{name}`")));
        }
        else if (project.CatalogVersion is null)
        {
            sb.AppendLine();
            sb.AppendLine(L(
                "> Los controladores propios de XAF tambien corren en estas pantallas. Nombrarlos " +
                "necesita el catalogo: `xaflogic catalog build` en una maquina con licencia DevExpress.",
                "> XAF's own controllers run on these screens too. Naming them needs the catalog: " +
                "`xaflogic catalog build` on a machine with a DevExpress licence."));
        }

        if (Catalog.CatalogTrust.Caveat(project, _spanish) is { } caveat)
        {
            sb.AppendLine();
            sb.AppendLine($"> {caveat}");
        }

        sb.AppendLine();
        sb.AppendLine(L(
            "> Un controlador listado aqui todavia puede apagarse solo en tiempo de ejecucion con " +
            "`Active[\"razon\"]`, que depende de los datos y del usuario. Esto es lo que XAF **carga** " +
            "en la pantalla, no lo que necesariamente hara algo.",
            "> A controller listed here can still switch itself off at run time through " +
            "`Active[\"reason\"]`, which depends on the data and the user. This is what XAF **loads** " +
            "onto the screen, not what will necessarily do something."));

        return new DocumentSection
        {
            Title = _l.Screens,
            FileName = $"{project.ProjectName}_Screens",
            Content = sb.ToString(),
            Description = string.Format(_l.ScreensDescription, project.ProjectName),
            Tags = "views,screens,controllers,activation,ui"
        };
    }

    /// <summary>
    /// Generates the overview section with system summary and relationships.
    /// </summary>
    private DocumentSection GenerateOverviewSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.SystemOverview}");
        sb.AppendLine();
        sb.AppendLine($"## {_l.Summary}");
        sb.AppendLine();
        sb.AppendLine($"- **{_l.Project}:** {project.ProjectName}");
        if (!string.IsNullOrWhiteSpace(project.TargetFramework))
            sb.AppendLine($"- **{_l.Framework}:** {project.TargetFramework}");
        sb.AppendLine($"- **ORM:** {project.OrmType}");
        sb.AppendLine($"- **{_l.BusinessEntitiesCount}:** {project.Entities.Count}");
        sb.AppendLine($"- **{_l.ControllersCount}:** {project.Controllers.Count}");
        sb.AppendLine($"- **{_l.NavigationGroups}:** {project.Navigation.Count}");
        if (project.ModelEditorInfo != null)
        {
            sb.AppendLine($"- **{_l.CustomViewsModelEditor}:** {project.ModelEditorInfo.Views.Count}");
            if (project.ModelEditorInfo.Options != null)
            {
                var opts = project.ModelEditorInfo.Options;
                var uiParts = new List<string>();
                if (opts.FormStyle != null) uiParts.Add(opts.FormStyle);
                if (opts.UIType != null) uiParts.Add(opts.UIType);
                if (opts.Skin != null) uiParts.Add(opts.Skin);
                if (uiParts.Count > 0)
                    sb.AppendLine($"- **{_l.UIStyle}:** {string.Join(", ", uiParts)}");
            }
        }
        sb.AppendLine();

        if (project.PackageReferences.Count > 0)
        {
            sb.AppendLine($"## {_l.MainPackages}");
            sb.AppendLine();
            foreach (var pkg in project.PackageReferences.Where(p =>
                         p.Contains("DevExpress") || p.Contains("ExpressApp")))
            {
                sb.AppendLine($"- {pkg}");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"## {_l.NavigationStructure}");
        sb.AppendLine();
        foreach (var nav in project.Navigation)
        {
            sb.AppendLine($"### {nav.GroupName}");
            foreach (var entity in nav.EntityClassNames)
            {
                var entityInfo = project.Entities.FirstOrDefault(e => e.ClassName == entity);
                var desc = entityInfo?.Description ?? "";
                sb.AppendLine($"- **{entity}** {(string.IsNullOrEmpty(desc) ? "" : $"- {desc}")}");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"## {_l.EntityRelationshipMap}");
        sb.AppendLine();

        // The map draws what each class declares. An association on a shared base is inherited by
        // every entity below it and listed under each of them, which is true of the objects and
        // wrong about the schema: one association drawn two hundred times is a map of the base
        // class, not of the application.
        foreach (var entity in project.Entities)
        {
            foreach (var rel in entity.Relationships.Where(r => r.InheritedFrom is null))
            {
                var relSymbol = rel.Type == RelationshipType.OneToMany ? "1:N" : "N:1";
                var aggLabel = rel.IsAggregated ? $" ({_l.Composition})" : "";
                sb.AppendLine($"- **{entity.ClassName}** --[{relSymbol}]--> **{rel.RelatedEntity}** via `{rel.PropertyName}`{aggLabel}");
            }
        }

        return new DocumentSection
        {
            Title = _l.SystemOverview,
            FileName = $"{project.ProjectName}_Overview",
            Content = sb.ToString(),
            Description = string.Format(_l.OverviewDescription, project.ProjectName),
            Tags = "overview,navigation,relationships,structure"
        };
    }

    /// <summary>
    /// Generates the business entities section.
    /// </summary>
    private DocumentSection GenerateEntitiesSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.BusinessEntities}");
        sb.AppendLine();

        foreach (var entity in project.Entities.OrderBy(e => e.NavigationGroup ?? "ZZZ").ThenBy(e => e.ClassName))
        {
            sb.AppendLine($"## {entity.ClassName}");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(entity.Description))
                sb.AppendLine($"*{entity.Description}*");

            sb.AppendLine();
            sb.AppendLine($"- **{_l.BaseType}:** `{entity.BaseType}`");
            if (!string.IsNullOrEmpty(entity.ModelCaption))
                sb.AppendLine($"- **{_l.CaptionModelEditor}:** {entity.ModelCaption}");
            if (!string.IsNullOrEmpty(entity.NavigationGroup))
                sb.AppendLine($"- **{_l.NavigationGroup}:** {entity.NavigationGroup}");
            if (!string.IsNullOrEmpty(entity.DefaultProperty))
                sb.AppendLine($"- **{_l.DisplayProperty}:** {entity.DefaultProperty}");
            sb.AppendLine($"- **{_l.Persistent}:** {(entity.IsPersistent ? _l.Yes : _l.No)}");
            if (entity.IsCloneable)
                sb.AppendLine($"- **{_l.Cloneable}:** {_l.Yes}");
            sb.AppendLine();

            if (entity.Properties.Count > 0)
            {
                sb.AppendLine($"### {_l.Properties}");
                sb.AppendLine();
                sb.AppendLine($"| {_l.Property} | {_l.Type} | {_l.Description} | {_l.Required} | {_l.Notes} |");
                sb.AppendLine("|-----------|------|-------------|-----------|-------|");

                foreach (var prop in entity.Properties.Where(p => !p.IsCollection))
                {
                    var notes = new List<string>();
                    if (prop.Size.HasValue) notes.Add($"Size:{prop.Size}");
                    if (prop.IsUnique) notes.Add(L("Unico", "Unique"));
                    if (prop.IsComputed) notes.Add(_l.Computed);
                    if (prop.ImmediatePostData) notes.Add("PostData");
                    if (!string.IsNullOrEmpty(prop.DisplayFormat)) notes.Add($"{_l.Format}:{prop.DisplayFormat}");
                    if (!string.IsNullOrEmpty(prop.DefaultValue)) notes.Add($"{_l.Default}:{prop.DefaultValue}");
                    if (!string.IsNullOrEmpty(prop.DataSourceCriteria)) notes.Add($"{_l.Filter}:{prop.DataSourceCriteria}");
                    // Which class the column comes from. It has been recorded since inherited
                    // properties began being folded and shown by nothing since, so every entity
                    // read as if it declared all of them -- and a reader who edits `CreatedOn`
                    // here is editing it for the whole application.
                    if (prop.InheritedFrom is { Length: > 0 }) notes.Add($"{Inherited(prop.InheritedFrom)}");

                    sb.AppendLine($"| `{prop.Name}` | `{prop.TypeName}` | {prop.Description ?? ""} | {(prop.IsRequired ? _l.Yes : "")} | {string.Join(", ", notes)} |");
                }
                sb.AppendLine();
            }

            if (entity.Relationships.Count > 0)
            {
                sb.AppendLine($"### {_l.Relationships}");
                sb.AppendLine();
                foreach (var rel in entity.Relationships.OrderByDescending(r => r.InheritedFrom is null))
                {
                    var relType = rel.Type == RelationshipType.OneToMany ? _l.OneToMany : _l.ManyToOne;
                    var aggLabel = rel.IsAggregated ? $" ({_l.CompositionAggregation})" : "";
                    sb.AppendLine($"- **{rel.PropertyName}** -> `{rel.RelatedEntity}` ({relType}){aggLabel}{Declarer(rel.InheritedFrom)}");
                }
                sb.AppendLine();
            }

            if (entity.ValidationRules.Count > 0)
            {
                sb.AppendLine($"### {_l.ValidationRules}");
                sb.AppendLine();
                foreach (var rule in entity.ValidationRules.OrderByDescending(r => r.InheritedFrom is null))
                {
                    var target = !string.IsNullOrEmpty(rule.TargetProperty) ? $" in `{rule.TargetProperty}`" : "";
                    sb.AppendLine($"- **{rule.RuleType}**{target}{RuleName(rule)}{DescribeRule(rule)}{Declarer(rule.InheritedFrom)}");
                }
                sb.AppendLine();
            }

            if (entity.AppearanceRules.Count > 0)
            {
                sb.AppendLine($"### {_l.AppearanceRules}");
                sb.AppendLine();
                foreach (var rule in entity.AppearanceRules.OrderByDescending(r => r.InheritedFrom is null))
                {
                    sb.AppendLine($"- {OpenAppearance(rule)}{DescribeAppearance(rule)}{Declarer(rule.InheritedFrom)}");
                }
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine();
        }

        return new DocumentSection
        {
            Title = _l.BusinessEntities,
            FileName = $"{project.ProjectName}_Entities",
            Content = sb.ToString(),
            Description = string.Format(_l.EntitiesDescription, project.ProjectName),
            Tags = "entities,properties,relationships,validation,business-objects"
        };
    }

    /// <summary>
    /// Generates the controllers and actions section.
    /// </summary>
    private DocumentSection GenerateControllersSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.ControllersAndActions}");
        sb.AppendLine();

        foreach (var controller in project.Controllers)
        {
            sb.AppendLine($"## {controller.ClassName}");
            sb.AppendLine();
            sb.AppendLine($"- **{_l.BaseType}:** `{controller.BaseControllerType}`");
            if (!string.IsNullOrEmpty(controller.TargetObjectType))
                sb.AppendLine($"- **{_l.TargetEntity}:** {controller.TargetObjectType}");
            if (!string.IsNullOrEmpty(controller.TargetViewType))
                sb.AppendLine($"- **{_l.ViewType}:** {controller.TargetViewType}");
            if (controller.ReferencedEntities.Count > 0)
                sb.AppendLine($"- **{_l.ReferencedEntities}:** {string.Join(", ", controller.ReferencedEntities)}");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(controller.BusinessLogicSummary))
            {
                sb.AppendLine($"### {_l.BusinessLogicSummary}");
                sb.AppendLine();
                sb.AppendLine(controller.BusinessLogicSummary);
                sb.AppendLine();
            }

            if (controller.Actions.Count > 0)
            {
                sb.AppendLine($"### {_l.Actions}");
                sb.AppendLine();
                foreach (var action in controller.Actions)
                {
                    sb.AppendLine($"#### {action.Caption ?? action.ActionId}");
                    sb.AppendLine();
                    sb.AppendLine($"- **ID:** `{action.ActionId}`");
                    sb.AppendLine($"- **{_l.Type}:** {action.ActionType}");
                    if (!string.IsNullOrEmpty(action.Category))
                        sb.AppendLine($"- **{_l.Category}:** {action.Category}");
                    if (!string.IsNullOrEmpty(action.ImageName))
                        sb.AppendLine($"- **{_l.Icon}:** {action.ImageName}");
                    if (!string.IsNullOrEmpty(action.ConfirmationMessage))
                        sb.AppendLine($"- **{_l.Confirmation}:** \"{action.ConfirmationMessage}\"");
                    if (!string.IsNullOrEmpty(action.ToolTip))
                        sb.AppendLine($"- **{_l.Tooltip}:** {action.ToolTip}");
                    sb.AppendLine();

                    if (!string.IsNullOrEmpty(action.BusinessLogicSummary))
                    {
                        sb.AppendLine($"**{_l.ActionBusinessLogic}:**");
                        sb.AppendLine();
                        sb.AppendLine(action.BusinessLogicSummary);
                        sb.AppendLine();
                    }

                    if (!string.IsNullOrEmpty(action.ExecuteMethodBody))
                    {
                        sb.AppendLine($"**{_l.ExecutionLogic}:**");
                        sb.AppendLine();
                        sb.AppendLine("```csharp");
                        var lines = action.ExecuteMethodBody.Split('\n');
                        var truncated = lines.Length > 100;
                        foreach (var line in lines.Take(100))
                            sb.AppendLine(line);
                        if (truncated)
                            sb.AppendLine($"// ... ({lines.Length - 100} {_l.MoreLines})");
                        sb.AppendLine("```");
                        sb.AppendLine();
                    }
                }
            }

            if (controller.Methods.Count > 0)
            {
                sb.AppendLine($"### {_l.MainMethods}");
                sb.AppendLine();
                foreach (var method in controller.Methods.Where(m => m.IsPublic || m.Name.Contains("Calcular") || m.Name.Contains("Procesar") || m.Name.Contains("Obtener")))
                {
                    var paramList = string.Join(", ", method.Parameters);
                    sb.AppendLine($"- **{method.Name}({paramList})** -> `{method.ReturnType}`");
                }
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine();
        }

        return new DocumentSection
        {
            Title = _l.ControllersAndActions,
            FileName = $"{project.ProjectName}_Controllers",
            Content = sb.ToString(),
            Description = string.Format(_l.ControllersDescription, project.ProjectName),
            Tags = "controllers,actions,business-logic,workflows"
        };
    }

    /// <summary>
    /// Generates the business rules section.
    /// </summary>
    private DocumentSection GenerateBusinessRulesSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.BusinessRules}");
        sb.AppendLine();

        // This index lists each rule under the class that wrote it, once. The entity sections
        // carry the same rule under everything that inherits it, which is what a reader of one
        // entity needs; repeating it here as well would turn the application's rule set into a
        // list whose length is a fact about its class hierarchy.
        sb.AppendLine($"## {_l.ValidationRules}");
        sb.AppendLine();
        foreach (var entity in project.Entities.Where(e => e.ValidationRules.Any(r => r.InheritedFrom is null)))
        {
            sb.AppendLine($"### {entity.ClassName}");
            foreach (var rule in entity.ValidationRules.Where(r => r.InheritedFrom is null))
            {
                sb.AppendLine($"- {rule.RuleType}{RuleName(rule)} {L("en", "on")} {rule.TargetProperty ?? _l.ClassLevel}{DescribeRule(rule)}");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"## {_l.ConditionalBehaviorRules}");
        sb.AppendLine();
        foreach (var entity in project.Entities.Where(e => e.AppearanceRules.Any(r => r.InheritedFrom is null)))
        {
            sb.AppendLine($"### {entity.ClassName}");
            foreach (var rule in entity.AppearanceRules.Where(r => r.InheritedFrom is null))
            {
                sb.AppendLine($"- {OpenAppearance(rule)}{DescribeAppearance(rule)}");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"## {_l.ComputedPropertiesDerived}");
        sb.AppendLine();
        foreach (var entity in project.Entities)
        {
            // Collections are association ends, not calculations. An XPO collection property is
            // getter-only, so it satisfied IsComputed and was filed under derived logic -- inviting
            // a reader to treat a persistent relationship as a formula.
            //
            // Declared here, like the rules above: one [PersistentAlias] on a shared base is one
            // formula, and listing it under every descendant would describe the application as
            // having as many calculations as it has classes.
            var computed = entity.Properties
                .Where(p => p.IsComputed && !p.IsCollection && p.InheritedFrom is null)
                .ToList();
            if (computed.Count == 0) continue;

            sb.AppendLine($"### {entity.ClassName}");
            foreach (var prop in computed)
            {
                var alias = !string.IsNullOrEmpty(prop.PersistentAlias) ? $" = `{prop.PersistentAlias}`" : "";
                sb.AppendLine($"- **{prop.Name}** (`{prop.TypeName}`){alias}");
            }
            sb.AppendLine();
        }

        var allRules = project.Entities.SelectMany(e => e.InferredBusinessRules).ToList();
        if (allRules.Count > 0)
        {
            sb.AppendLine($"## {_l.ExplicitBusinessRules}");
            sb.AppendLine();
            foreach (var group in allRules.GroupBy(r => r.Category))
            {
                sb.AppendLine($"### {group.Key}");
                foreach (var rule in group)
                {
                    sb.AppendLine($"- {rule.Description}");
                }
                sb.AppendLine();
            }
        }

        return new DocumentSection
        {
            Title = _l.BusinessRules,
            FileName = $"{project.ProjectName}_BusinessRules",
            Content = sb.ToString(),
            Description = string.Format(_l.BusinessRulesDescription, project.ProjectName),
            Tags = "business-rules,validation,computed,conditional,logic"
        };
    }

    /// <summary>
    /// Generates module configuration and seed-data section.
    /// </summary>
    private DocumentSection GenerateConfigurationSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.ConfigurationAndSeedData}");
        sb.AppendLine();

        if (project.ModuleInfo != null)
        {
            sb.AppendLine($"## {_l.MainModule}");
            sb.AppendLine();
            sb.AppendLine($"- **{_l.Class}:** {project.ModuleInfo.ModuleClassName}");
            sb.AppendLine();

            if (project.ModuleInfo.RequiredModules.Count > 0)
            {
                sb.AppendLine($"### {_l.RequiredModules}");
                foreach (var mod in project.ModuleInfo.RequiredModules)
                    sb.AppendLine($"- {mod}");
                sb.AppendLine();
            }

            if (project.ModuleInfo.RegisteredTypes.Count > 0)
            {
                sb.AppendLine($"### {_l.RegisteredTypes}");
                foreach (var type in project.ModuleInfo.RegisteredTypes)
                    sb.AppendLine($"- {type}");
                sb.AppendLine();
            }
        }

        if (project.SeedData.Count > 0)
        {
            sb.AppendLine($"## {_l.SeedData}");
            sb.AppendLine();
            sb.AppendLine(_l.SeedDataDescription);
            sb.AppendLine();

            foreach (var seed in project.SeedData)
            {
                sb.AppendLine($"### {seed.Description}");
                sb.AppendLine();
                sb.AppendLine($"**{_l.Entity}:** `{seed.EntityType}` | **{_l.Method}:** `{seed.MethodName}`");
                sb.AppendLine();

                if (seed.Records.Count > 0)
                {
                    var allKeys = seed.Records.SelectMany(r => r.PropertyValues.Keys).Distinct().ToList();
                    if (allKeys.Count > 0)
                    {
                        sb.AppendLine("| " + string.Join(" | ", allKeys) + " |");
                        sb.AppendLine("| " + string.Join(" | ", allKeys.Select(_ => "---")) + " |");
                        foreach (var record in seed.Records)
                        {
                            var values = allKeys.Select(k => record.PropertyValues.GetValueOrDefault(k, ""));
                            sb.AppendLine("| " + string.Join(" | ", values) + " |");
                        }
                        sb.AppendLine();
                    }
                }

                if (!string.IsNullOrEmpty(seed.RawSourceCode))
                {
                    // A heading rather than a <details> fold. The fold only opens in a renderer that
                    // passes HTML through, and everywhere else -- a Word or PDF export, a plain
                    // Markdown viewer, a model reading the file -- the wrapper is literal text and the
                    // label stops being a label. This costs the fold on GitHub, which is the trade:
                    // these files are read far more often than they are scrolled.
                    sb.AppendLine($"#### {_l.SourceCodeOf} {seed.MethodName}");
                    sb.AppendLine();
                    sb.AppendLine("```csharp");
                    sb.AppendLine(seed.RawSourceCode);
                    sb.AppendLine("```");
                    sb.AppendLine();
                }
            }
        }

        return new DocumentSection
        {
            Title = _l.ConfigurationAndSeedData,
            FileName = $"{project.ProjectName}_Configuration",
            Content = sb.ToString(),
            Description = string.Format(_l.ConfigurationDescription, project.ProjectName),
            Tags = "configuration,seed-data,module,initialization,setup"
        };
    }

    /// <summary>
    /// Generates application navigation section.
    /// </summary>
    private DocumentSection GenerateNavigationSection(ExtractedProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.NavigationStructure}");
        sb.AppendLine();
        sb.AppendLine($"## {_l.ApplicationMenu}");
        sb.AppendLine();

        foreach (var nav in project.Navigation)
        {
            sb.AppendLine($"### {nav.GroupName}");
            sb.AppendLine();
            foreach (var entityName in nav.EntityClassNames)
            {
                var entity = project.Entities.FirstOrDefault(e => e.ClassName == entityName);
                if (entity == null) continue;

                sb.AppendLine($"#### {entityName}");
                if (!string.IsNullOrEmpty(entity.Description))
                    sb.AppendLine($"*{entity.Description}*");
                sb.AppendLine();

                // Own columns first: eight slots shared with a base the whole application derives
                // from would otherwise name the base's columns under every entity in the menu.
                var main = entity.Properties
                    .Where(p => !p.IsCollection && p.VisibleInListView)
                    .OrderByDescending(p => p.InheritedFrom is null)
                    .Take(8)
                    .Select(p => p.Name);

                sb.AppendLine($"- **{_l.MainProperties}:** {string.Join(", ", main)}");
                if (entity.Relationships.Count > 0)
                    sb.AppendLine($"- **{_l.Relationships}:** {string.Join(", ", entity.Relationships.Select(r => $"{r.PropertyName}→{r.RelatedEntity}"))}");
                sb.AppendLine();
            }
        }

        var orphans = project.Entities.Where(e => string.IsNullOrEmpty(e.NavigationGroup)).ToList();
        if (orphans.Count > 0)
        {
            sb.AppendLine($"### {_l.WithoutNavigationGroup}");
            sb.AppendLine();
            foreach (var entity in orphans)
            {
                sb.AppendLine($"- **{entity.ClassName}** (`{entity.BaseType}`)");
            }
        }

        return new DocumentSection
        {
            Title = _l.NavigationStructure,
            FileName = $"{project.ProjectName}_Navigation",
            Content = sb.ToString(),
            Description = string.Format(_l.NavigationDescription, project.ProjectName),
            Tags = "navigation,menu,structure,ui"
        };
    }

    /// <summary>
    /// Generates Model Editor customization section from xafml metadata.
    /// </summary>
    private DocumentSection GenerateModelEditorSection(ExtractedProject project)
    {
        var model = project.ModelEditorInfo!;
        var sb = new StringBuilder();
        sb.AppendLine($"# {project.ProjectName} - {_l.ModelEditorCustomizations}");
        sb.AppendLine();

        if (model.Options != null)
        {
            sb.AppendLine($"## {_l.ApplicationOptions}");
            sb.AppendLine();
            if (model.Options.UIType != null) sb.AppendLine($"- **{_l.UITypeLabel}:** {model.Options.UIType}");
            if (model.Options.FormStyle != null) sb.AppendLine($"- **{_l.FormStyleLabel}:** {model.Options.FormStyle}");
            if (model.Options.Skin != null) sb.AppendLine($"- **{_l.VisualTheme}:** {model.Options.Skin}");
            if (model.Options.RequiredFieldMark != null) sb.AppendLine($"- **{_l.RequiredFieldMark}:** {model.Options.RequiredFieldMark}");
            sb.AppendLine();
        }

        if (model.BOModelClasses.Count > 0)
        {
            sb.AppendLine($"## {_l.BOModelCustomizations}");
            sb.AppendLine();
            sb.AppendLine($"| {_l.Class} | {_l.Caption} | {_l.Cloneable} | {_l.Other} |");
            sb.AppendLine("|-------|---------|----------|-------|");
            foreach (var cls in model.BOModelClasses)
            {
                var others = cls.CustomAttributes.Count > 0
                    ? string.Join(", ", cls.CustomAttributes.Select(kv => $"{kv.Key}={kv.Value}"))
                    : "";
                sb.AppendLine($"| `{cls.ClassName}` | {cls.Caption ?? ""} | {(cls.IsCloneable ? _l.Yes : "")} | {others} |");
            }
            sb.AppendLine();
        }

        if (model.Views.Count > 0)
        {
            sb.AppendLine($"## {_l.ViewCustomizations}");
            sb.AppendLine();
            foreach (var view in model.Views)
            {
                sb.AppendLine($"### {view.Id} ({view.ViewType})");
                sb.AppendLine();
                if (view.Caption != null) sb.AppendLine($"- **{_l.Caption}:** {view.Caption}");
                if (view.AllowEdit.HasValue) sb.AppendLine($"- **{_l.Editable}:** {(view.AllowEdit.Value ? _l.Yes : _l.No)}");
                if (view.AllowDelete.HasValue) sb.AppendLine($"- **{_l.AllowDelete}:** {(view.AllowDelete.Value ? _l.Yes : _l.No)}");
                if (view.AllowNew.HasValue) sb.AppendLine($"- **{_l.AllowCreate}:** {(view.AllowNew.Value ? _l.Yes : _l.No)}");
                if (view.Criteria != null) sb.AppendLine($"- **{_l.FilterCriteria}:** `{view.Criteria}`");
                if (view.EditorTypeName != null) sb.AppendLine($"- **{_l.CustomEditor}:** `{view.EditorTypeName}`");

                if (view.Columns.Count > 0)
                {
                    sb.AppendLine();
                    sb.AppendLine($"**{_l.ConfiguredColumns}:**");
                    sb.AppendLine();
                    sb.AppendLine($"| {_l.Property} | {_l.Order} | {_l.Width} | {_l.Sorting} | {_l.Caption} |");
                    sb.AppendLine("|-----------|-------|-------|-------------|---------|");
                    foreach (var col in view.Columns.OrderBy(c => c.Index ?? 999))
                    {
                        sb.AppendLine($"| `{col.PropertyName ?? col.Id}` | {col.Index?.ToString() ?? ""} | {col.Width?.ToString() ?? ""} | {col.SortOrder ?? ""} | {col.Caption ?? ""} |");
                    }
                    sb.AppendLine();
                }

                if (view.Filters.Count > 0)
                {
                    sb.AppendLine($"**{_l.PredefinedFilters}:**");
                    sb.AppendLine();
                    foreach (var filter in view.Filters)
                    {
                        sb.AppendLine($"- **{filter.Caption ?? filter.Id}**: `{filter.Criteria}`");
                    }
                    sb.AppendLine();
                }
            }
        }

        if (model.NavigationItems != null && model.NavigationItems.Groups.Count > 0)
        {
            sb.AppendLine($"## {_l.NavigationModelEditor}");
            sb.AppendLine();
            if (model.NavigationItems.NavigationStyle != null)
                sb.AppendLine($"- **{_l.Style}:** {model.NavigationItems.NavigationStyle}");
            if (model.NavigationItems.StartupNavigationItem != null)
                sb.AppendLine($"- **{_l.StartupView}:** {model.NavigationItems.StartupNavigationItem}");
            sb.AppendLine();

            foreach (var group in model.NavigationItems.Groups)
            {
                sb.AppendLine($"### {group.Caption ?? group.Id}");
                foreach (var item in group.Items.OrderBy(i => i.Index ?? 999))
                {
                    var icon = item.ImageName != null ? $" ({_l.Icon}: {item.ImageName})" : "";
                    var viewRef = item.ViewId != null ? $" -> `{item.ViewId}`" : "";
                    sb.AppendLine($"- **{item.Caption ?? item.Id}**{viewRef}{icon}");
                }
                sb.AppendLine();
            }
        }

        if (model.SchemaModules.Count > 0)
        {
            sb.AppendLine($"## {_l.RegisteredSchemaModules}");
            sb.AppendLine();
            foreach (var mod in model.SchemaModules)
            {
                sb.AppendLine($"- **{mod.Name}** v{mod.Version}");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"## {_l.ProcessedXafmlFiles}");
        sb.AppendLine();
        foreach (var f in model.SourceFiles)
        {
            sb.AppendLine($"- `{Path.GetFileName(f)}` ({Path.GetDirectoryName(f)})");
        }

        return new DocumentSection
        {
            Title = _l.ModelEditorCustomizations,
            FileName = $"{project.ProjectName}_ModelEditor",
            Content = sb.ToString(),
            Description = string.Format(_l.ModelEditorDescription, project.ProjectName),
            Tags = "model-editor,xafml,views,columns,filters,ui-customization"
        };
    }
}
