using System.Text;

namespace XafLogicExplainer.Core.Sinks;

/// <summary>
/// Writes generated content into a file without destroying anything a human put there.
/// </summary>
/// <remarks>
/// <c>AGENTS.md</c> and <c>CLAUDE.md</c> are files developers write in by hand. A tool that
/// overwrites them wholesale gets run exactly once, because the first regeneration silently deletes
/// the notes someone spent an afternoon on.
/// <para>
/// So generated content lives between markers. On every run the region between them is replaced and
/// everything outside is preserved. A file that already exists without markers keeps all of its
/// content and gains the generated block at the end.
/// </para>
/// </remarks>
public static class ManagedBlock
{
    /// <summary>Opening marker. Also the signal that a file is already under management.</summary>
    public const string BeginMarker = "<!-- BEGIN GENERATED BY XAF LOGIC EXPLAINER -->";

    /// <summary>Closing marker.</summary>
    public const string EndMarker = "<!-- END GENERATED BY XAF LOGIC EXPLAINER -->";

    private const string EditWarning =
        "<!-- Everything between these markers is generated. Edits here are overwritten;\n" +
        "     text outside them is preserved across runs. -->";

    /// <summary>
    /// Produces the new full contents of a file, given whatever it holds today.
    /// </summary>
    /// <param name="existingContent">Current file contents, or null when the file is new.</param>
    /// <param name="generatedContent">The content to place inside the managed block.</param>
    /// <returns>The complete text to write.</returns>
    public static string Apply(string? existingContent, string generatedContent)
    {
        var block = BuildBlock(generatedContent);

        if (string.IsNullOrWhiteSpace(existingContent))
            return Compose(before: "", block, after: "");

        var beginIndex = existingContent.IndexOf(BeginMarker, StringComparison.Ordinal);

        // The end is looked for after the beginning. A note above the block that quotes the closing
        // marker is the developer's text, not the end of a block that has not started yet, and
        // taking it for one appended a new block below on every run.
        var endIndex = beginIndex < 0
            ? -1
            : existingContent.IndexOf(EndMarker, beginIndex + BeginMarker.Length, StringComparison.Ordinal);

        // Already managed: swap the region in place, keeping the human's text on both sides.
        if (beginIndex >= 0 && endIndex > beginIndex)
        {
            return Compose(
                before: existingContent[..beginIndex],
                block,
                after: existingContent[(endIndex + EndMarker.Length)..]);
        }

        // A begin marker with no end (someone edited it, or a previous run was interrupted).
        // Truncating at the marker would delete whatever followed, so append instead and leave the
        // damaged region visible rather than silently discarding text.
        return Compose(before: existingContent, block, after: "");
    }

    /// <summary>
    /// Joins the surviving human text and the generated block into a canonical layout.
    /// </summary>
    /// <remarks>
    /// Regenerating must be byte-identical when nothing changed. Concatenating the three parts
    /// as-is is not: the block ends with a newline and the text after the closing marker begins
    /// with one, so every run added a blank line and the file grew forever. In a repository that
    /// shows up as a one-line diff on every regeneration, which trains people to stop reading them.
    /// <para>
    /// Trimming each part and re-joining with fixed separators makes the output a pure function of
    /// its inputs.
    /// </para>
    /// </remarks>
    private static string Compose(string before, string block, string after)
    {
        var sb = new StringBuilder();

        var trimmedBefore = before.TrimEnd();
        if (trimmedBefore.Length > 0)
        {
            sb.Append(trimmedBefore);
            sb.Append("\n\n");
        }

        sb.Append(block.TrimEnd());

        var trimmedAfter = after.TrimStart();
        if (trimmedAfter.Length > 0)
        {
            sb.Append("\n\n");
            sb.Append(trimmedAfter.TrimEnd());
        }

        sb.Append('\n');
        return sb.ToString();
    }

    /// <summary>
    /// Whether a file is already under management.
    /// </summary>
    public static bool IsManaged(string? content) =>
        content is not null && content.Contains(BeginMarker, StringComparison.Ordinal);

    private static string BuildBlock(string generatedContent)
    {
        var sb = new StringBuilder();
        sb.AppendLine(BeginMarker);
        sb.AppendLine(EditWarning);
        sb.AppendLine();
        sb.AppendLine(Quote(generatedContent.TrimEnd()));
        sb.AppendLine();
        sb.AppendLine(EndMarker);
        return sb.ToString();
    }

    private const string QuotedBeginMarker = "<!-- (quoted) BEGIN GENERATED BY XAF LOGIC EXPLAINER -->";

    private const string QuotedEndMarker = "<!-- (quoted) END GENERATED BY XAF LOGIC EXPLAINER -->";

    /// <summary>
    /// Makes a marker that appears inside generated content stop being one.
    /// </summary>
    /// <remarks>
    /// Generated content copies text out of the application (criteria, captions, comments), and any
    /// of it can hold a marker. Left as it was, the next run found the quoted END first: everything
    /// after it was kept as the developer's text, and the file gained a block per regeneration. The
    /// quoted form still reads as what it is and no longer matches.
    /// </remarks>
    private static string Quote(string generatedContent) => generatedContent
        .Replace(BeginMarker, QuotedBeginMarker, StringComparison.Ordinal)
        .Replace(EndMarker, QuotedEndMarker, StringComparison.Ordinal);
}
