namespace XafLogicExplainer.Core.Models;

/// <summary>
/// Where a view can appear.
/// </summary>
public enum ViewNesting
{
    /// <summary>Shown in a window of its own, reached from navigation or an action.</summary>
    Root,

    /// <summary>Shown inside another view, by a property editor.</summary>
    Nested,

    /// <summary>Both, depending on how it was opened.</summary>
    Either,
}

/// <summary>
/// Where a view came from.
/// </summary>
public enum ViewOrigin
{
    /// <summary>Generated by XAF from the business class. It exists in no file.</summary>
    Generated,

    /// <summary>Generated, and then customized in the Model Editor.</summary>
    Customized,

    /// <summary>Present only in the Model Editor — a cloned or hand-written view.</summary>
    ModelOnly,
}

/// <summary>
/// One screen of the application, and the logic that runs on it.
/// </summary>
/// <remarks>
/// Most of these exist in no file. XAF generates a list, detail and lookup view for every business
/// class and a nested list view for every collection, and the Model Editor stores only the ones
/// somebody changed — so reading the <c>.xafml</c> alone finds a fraction of the application's
/// screens, and reading the C# finds none of them.
/// </remarks>
public sealed class ExtractedView
{
    /// <summary>The view identifier XAF uses, e.g. <c>Order_ListView</c>.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Which kind of view this is.</summary>
    public ModelViewType ViewType { get; set; }

    /// <summary>Business class shown, or null for a dashboard.</summary>
    public string? ObjectType { get; set; }

    /// <summary>Where this view can appear.</summary>
    public ViewNesting Nesting { get; set; }

    /// <summary>Whether it is generated, customized or hand-written.</summary>
    public ViewOrigin Origin { get; set; }

    /// <summary>Caption from the Model Editor, when one was set.</summary>
    public string? Caption { get; set; }

    /// <summary>For a nested list view, the class whose property shows it.</summary>
    public string? OwnerEntity { get; set; }

    /// <summary>For a nested list view, the collection property that shows it.</summary>
    public string? OwnerProperty { get; set; }

    /// <summary>Whether a navigation item opens this view.</summary>
    public bool InNavigation { get; set; }

    /// <summary>The controllers XAF activates here, and why.</summary>
    public List<ViewActivation> Activates { get; set; } = [];
}

/// <summary>
/// One controller that runs on a view, and what makes it run there.
/// </summary>
public sealed class ViewActivation
{
    /// <summary>Controller class name.</summary>
    public string Controller { get; set; } = string.Empty;

    /// <summary>Project the controller was extracted from, or the assembly it ships in.</summary>
    public string? SourceProject { get; set; }

    /// <summary>
    /// Whether DevExpress ships this controller rather than this team having written it.
    /// </summary>
    /// <remarks>
    /// The distinction an agent most needs: framework behaviour is inherited and cannot be edited
    /// here, and a request to "change what this screen does" means something different for each.
    /// </remarks>
    public bool Framework { get; set; }

    /// <summary>Official one-line description, for a framework controller.</summary>
    public string? Summary { get; set; }

    /// <summary>Official documentation page, for a framework controller.</summary>
    public string? DocumentationUrl { get; set; }

    /// <summary>
    /// Why it matches, in the terms XAF checks: one entry per condition that had something to say.
    /// </summary>
    /// <remarks>
    /// An empty list is the loudest result — it means the controller restricts nothing and
    /// therefore runs on every view in the application.
    /// </remarks>
    public List<ActivationReason> Reasons { get; set; } = [];

    /// <summary>Actions of this controller that also pass their own targeting.</summary>
    public List<string> Actions { get; set; } = [];

    /// <summary>
    /// Controllers this one displaces, which therefore do not run here.
    /// </summary>
    /// <remarks>
    /// XAF activates only the most derived controller of an inheritance chain, so a class extending
    /// a shipped controller switches the original off application-wide. Worth naming: it is the
    /// difference between adding behaviour beside the framework's and replacing it.
    /// </remarks>
    public List<string> Replaces { get; set; } = [];
}

/// <summary>
/// One of the four tests XAF ands together in <c>IsFitToView</c>.
/// </summary>
public enum ActivationCondition
{
    /// <summary>Whether the view is root or nested.</summary>
    Nesting,

    /// <summary>Which view class it is.</summary>
    ViewType,

    /// <summary>Which business class its objects are.</summary>
    ObjectType,

    /// <summary>Whether its id is one the controller names.</summary>
    ViewId,
}

/// <summary>
/// One condition that held, and what made it hold.
/// </summary>
/// <remarks>
/// Kept as data rather than as a sentence because the same extraction is rendered into an English
/// page, an English tool response and a Spanish document. A pre-worded reason would leave English
/// fragments inside the Spanish one.
/// </remarks>
public sealed class ActivationReason
{
    /// <summary>Which of the four conditions this is.</summary>
    public ActivationCondition Condition { get; set; }

    /// <summary>What the controller requires, e.g. <c>ObjectView</c> or a base class name.</summary>
    public string Required { get; set; } = string.Empty;

    /// <summary>What the view actually is, when that differs from what was required.</summary>
    public string? Actual { get; set; }
}
